### ISSUE TITLE
Unable to getting a e-invoice summary report.

### ISSUE THREAD

**Issue by rvikas1997** [resilient-tech/india-compliance#1013]
### Information about bug

AttributeError: 'str' object has no attribute 'company' Possible source of error: india_compliance (app)

### App Versions
```
{
	"erpnext": "15.0.0-dev",
	"frappe": "15.0.0-dev",
	"india_compliance": "15.0.0-dev"
}
```
### Route
```
query-report/e-Invoice Summary
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 83, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1671, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/number_card/number_card.py", line 23, in get_pending_e_invoices_count
    return get_e_invoice_summary_count(filters)
  File "apps/india_compliance/india_compliance/gst_india/number_card/number_card.py", line 43, in get_e_invoice_summary_count
    e_invoice_summary = get_data(filters)
  File "apps/india_compliance/india_compliance/gst_india/report/e_invoice_summary/e_invoice_summary.py", line 80, in get_data
    e_invoice_applicability_date = get_e_invoice_applicability_date(
  File "apps/india_compliance/india_compliance/gst_india/utils/e_invoice.py", line 347, in get_e_invoice_applicability_date
    if doc.company == row.company:
AttributeError: 'str' object has no attribute 'company'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"filters": "{\"company\":\"Resilient Test\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/india_compliance.gst_india.number_card.number_card.get_pending_e_invoices_count",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'str' object has no attribute 'company'",
	"_exc_source": "india_compliance (app)"
}
```

### Version

ERPNext: v14.x.x-develop
Frappe Framework: v15.x.x-develop
India Compliance: v15.0.0-dev 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Hello,

Thanks for reporting. We will fix this issue.
