### ISSUE TITLE
Unable to update E-way bill- "Update Vehicle Info" if want to change mode of transport

### ISSUE THREAD

**Issue by Sunilmehra21** [resilient-tech/india-compliance#1023]
In ERP Next v14, update vehicle info option is available in Sales invoice>E-way bill. but if mode of transport is changed like road to train that update vehicle info form have missing some mandatory field like place of change, RR No. & Date. so without fill this information ERP is unable to update E-way bill.

**For ref. below is vehicle update form in ERP**
![image](https://github.com/resilient-tech/india-compliance/assets/119653765/dfa56418-19f5-4118-9732-cdbaa0971f18)

And below is actual vehicle update form in E-way bill portal.
![image](https://github.com/resilient-tech/india-compliance/assets/119653765/f6bb642a-b639-41ef-b2c9-cf16e0f2b4ae)

So please fix the issue.

**version details**
Installed Apps
Ecommerce Integrations: v1.17.4 (HEAD)

ERPNext: v14.29.1 (HEAD)

erpnext_org_structure: v0.0.1 (HEAD)

Frappe Framework: v14.40.1 (HEAD)

Frappe HR: v14.5.0 (HEAD)

India Compliance: v14.10.4 (HEAD)

Payments: v0.0.1 (HEAD)

Rangsutra: v0.0.1 (HEAD)

Rangsutra Custom Reports: v0.0.1 (HEAD)

Regards
**Sunil**

**Comment by Sunilmehra21** [comment]
@ljain112 Place of change and state field is now available but when i try to update Part-B an server error is coming. 
![image](https://github.com/resilient-tech/india-compliance/assets/119653765/bfa11a68-6a69-44e8-bae1-9fdd50a2972d)
![image](https://github.com/resilient-tech/india-compliance/assets/119653765/b2d103fc-891a-4f25-8e5c-daaf438c9657)
below is error log
### App Versions
```
{
	"ecommerce_integrations": "1.19.1",
	"erpnext": "14.46.5",
	"erpnext_org_structure": "0.0.1",
	"frappe": "14.54.0",
	"hrms": "14.16.0",
	"india_compliance": "14.19.2",
	
}
```
### Route
```
Form/Sales Invoice/SI/FY23/BK0818
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/india_compliance/india_compliance/gst_india/utils/e_waybill.py", line 296, in update_vehicle_info
    "vehicle_no": values.vehicle_no.replace(" ", ""),
AttributeError: 'NoneType' object has no attribute 'replace'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Sales Invoice",
		"docname": "SI/FY23/BK0818",
		"values": "{\"ewaybill\":\"741385992082\",\"place_of_change\":\"Bikaner\",\"lr_no\":\"1007136199\",\"mode_of_transport\":\"Rail\",\"state\":\"Rajasthan\",\"gst_vehicle_type\":\"Regular\",\"lr_date\":\"2023-11-27\",\"reason\":\"First Time\",\"update_e_waybill_data\":1}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/india_compliance.gst_india.utils.e_waybill.update_vehicle_info"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute 'replace'"
}
```

Please check and fix the issue.

Regards
Sunil Mehra
