### ISSUE TITLE
Not allowed to save any documents 

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#1043]
### Information about bug

not allowd to save any documents

### Version

ERPNext: v14.38.0 (version-14)

Frappe Framework: v14.48.1 (version-14)

Frappe HR: v14.10.5 (version-14)

India Compliance: v14.16.2 (version-14)

### Relevant log output / Stack trace / Full Error Message.

```shell
ailed to load resource: the server responded with a status of 417 ()
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 307, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 329, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1053, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 917, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1279, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1263, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 930, in validate_transaction
    if validate_mandatory_fields(doc, ("company_gstin", "place_of_supply")) is False:
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 147, in validate_mandatory_fields
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 534, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 502, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 451, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: <strong>Company GSTIN</strong> is a mandatory field for GST Transactions
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Refer following post.
https://discuss.frappe.io/t/india-compliance-unable-to-generate-sales-or-purchase-transactions/94592

**Comment by dineshpanchal93** [comment]
Thanks @vorasmit
