### ISSUE TITLE
State Validation

### ISSUE THREAD

**Issue by IBSLPUNE** [resilient-tech/india-compliance#1088]
### Information about bug

We are unable to sync amazon orders,as india compliance is invalidating the states synced in the data.

### Version

Erpnext ,Frappe 14

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Can you please share the complete traceback of the error?
Are you using ecommerce_integrations app?

**Comment by IBSLPUNE** [comment]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1075, in perform_job
    rv = job.perform()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 854, in perform
    self._result = self._execute()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 877, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 192, in execute_job
    retval = method(**kwargs)
  File "/home/frappe/frappe-bench/apps/ecommerce_integrations/ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_repository.py", line 506, in get_orders
    return ar.get_orders(created_after)
  File "/home/frappe/frappe-bench/apps/ecommerce_integrations/ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_repository.py", line 464, in get_orders
    sales_order = self.create_sales_order(order)
  File "/home/frappe/frappe-bench/apps/ecommerce_integrations/ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_repository.py", line 400, in create_sales_order
    create_address(order, customer_name)
  File "/home/frappe/frappe-bench/apps/ecommerce_integrations/ecommerce_integrations/amazon/doctype/amazon_sp_api_settings/amazon_repository.py", line 386, in create_address
    make_address.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1053, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 917, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1279, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1263, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/address.py", line 16, in validate
    validate_state(doc)
  File "/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/address.py", line 53, in validate_state
    frappe.throw(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 534, in throw
    msgprint(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 502, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 451, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Please select a valid State from available options

**Comment by IBSLPUNE** [comment]
> Can you please share the complete traceback of the error? Are you using ecommerce_integrations app?

I am using ecommerce integrations app,viz. amazon.

**Comment by vorasmit** [comment]
The issue relates to the e-commerce Integrations App. It should create an address with the correct state. This needs to be precise as the Place of supply is decided based on this. Mapping of Amazon Sates to ERP states needs to be in place there.

**Comment by vorasmit** [comment]
You may reference and create issue in the relevant repo if required:
https://github.com/frappe/ecommerce_integrations/
