### ISSUE TITLE
Unable to Save sales invoice and purchase invoice after Update.

### ISSUE THREAD

**Issue by bhargav007n** [resilient-tech/india-compliance#1096]
### Information about bug

Unable to create sales and purchase invoice after updating india compliance.
Throwing up following error "AttributeError: 'GSTSettings' object has no attribute 'validate_gstin_status'. "
And updated only India_Compliance via 'git pull'

### Version

	"erpnext": "14.34.3",
	"frappe": "14.44.0",
	"hrms": "14.10.0",
	"india_compliance": "14.16.2",
	"payments": "0.0.1"

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.34.3",
	"frappe": "14.44.0",
	"hrms": "14.10.0",
	"india_compliance": "14.16.2",
	"payments": "0.0.1"
}
```
### Route
```
Form/Sales Invoice/new-sales-invoice-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1620, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1051, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 915, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1277, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/sales_invoice.py", line 49, in validate
    if validate_transaction(doc) is False:
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 960, in validate_transaction
    validate_gstin(gstin, doc.get("posting_date") or doc.get("transaction_date"))
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 910, in validate_gstin
    if not settings.validate_gstin_status:
AttributeError: 'GSTSettings' object has no attribute 'validate_gstin_status'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Sales Invoice\",\"name\":\"new-sales-invoice-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"triotech.bhargav@gmail.com\",\"naming_series\":\"TTMS/23-24/\",\"e_waybill_status\":\"\",\"company\":\"TrioTech Manufacturing Systems\",\"posting_date\":\"2023-10-03\",\"set_posting_time\":1,\"is_pos\":0,\"is_consolidated\":0,\"is_return\":0,\"reason_for_issuing_document\":\"\",\"update_billed_amount_in_sales_order\":0,\"is_debit_note\":0,\"is_reverse_charge\":0,\"is_export_with_gst\":0,\"currency\":\"INR\",\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"ignore_pricing_rule\":0,\"update_stock\":1,\"use_company_roundoff_cost_center\":0,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"is_cash_or_non_trade_discount\":0,\"total_billing_amount\":0,\"allocate_advances_automatically\":0,\"write_off_outstanding_amount_automatically\":0,\"redeem_loyalty_points\":0,\"territory\":\"All Territories\",\"ignore_default_payment_terms_template\":0,\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"letter_head\":\"Triotech\",\"group_same_items\":0,\"invoice_copy\":\"Original for Recipient\",\"mode_of_transport\":\"Road\",\"lr_date\":\"2023-10-03\",\"gst_vehicle_type\":\"Regular\",\"status\":\"Draft\",\"einvoice_status\":\"\",\"customer_group\":\"All Customer Groups\",\"is_internal_customer\":0,\"is_discounted\":0,\"repost_required\":0,\"items\":[{\"owner\":\"triotech.bhargav@gmail.com\",\"docstatus\":0,\"idx\":1,\"has_item_scanned\":0,\"item_code\":\"01-0164-000\",\"dpo\":0,\"ert\":0,\"item_name\":\"Z RIGHT END HEIGHT PLATE ST50200 - 15108P0006\",\"po_reference\":\"3500271965\",\"description\":\"Z RIGHT END HEIGHT PLATE ST50200 - 15108P0006\",\"gst_hsn_code\":\"84669310\",\"is_nil_exempt\":0,\"is_non_gst\":0,\"item_group\":\"ACE_Manufacturing\",\"image\":\"\",\"qty\":10,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":10,\"price_list_rate\":375,\"base_price_list_rate\":375,\"margin_type\":\"Amount\",\"margin_rate_or_amount\":37,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":-37,\"base_rate_with_margin\":0,\"rate\":412,\"amount\":4120,\"item_tax_template\":\"GST 18% (Sales) - TMS\",\"base_rate\":412,\"base_amount\":4120,\"stock_uom_rate\":0,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":412,\"net_amount\":4120,\"base_net_rate\":412,\"base_net_amount\":4120,\"taxable_value\":0,\"delivered_by_supplier\":0,\"income_account\":\"Sales - TMS\",\"is_fixed_asset\":0,\"expense_account\":\"RM Purchase - TMS\",\"enable_deferred_revenue\":0,\"weight_per_unit\":0,\"total_weight\":0,\"weight_uom\":\"Kg\",\"warehouse\":\"Finished Goods - TMS\",\"incoming_rate\":0,\"allow_zero_valuation_rate\":0,\"item_tax_rate\":\"{\\\"Output Tax SGST - TMS\\\": 9.0, \\\"Output Tax CGST - TMS\\\": 9.0, \\\"Output Tax IGST - TMS\\\": 18.0}\",\"actual_batch_qty\":0,\"actual_qty\":-16,\"sales_order\":\"SAL-ORD-2023-00324\",\"so_detail\":\"ced1d910ff\",\"delivered_qty\":0,\"cost_center\":\"Main - TMS\",\"page_break\":0,\"parent\":\"new-sales-invoice-1\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\",\"__islocal\":1,\"__unsaved\":1,\"name\":\"new-sales-invoice-item-2\"}],\"taxes\":[{\"docstatus\":0,\"doctype\":\"Sales Taxes and Charges\",\"name\":\"new-sales-taxes-and-charges-6\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"triotech.bhargav@gmail.com\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"cost_center\":\"Main - TMS\",\"account_currency\":\"INR\",\"dont_recompute_tax\":0,\"parent\":\"new-sales-invoice-1\",\"parentfield\":\"taxes\",\"parenttype\":\"Sales Invoice\",\"idx\":1,\"row_id\":\"\",\"account_head\":\"Output Tax CGST - TMS\",\"description\":\"Output Tax CGST\",\"rate\":0,\"tax_amount\":370.8,\"total\":4490.8,\"tax_amount_after_discount_amount\":370.8,\"base_tax_amount\":370.8,\"base_total\":4490.8,\"base_tax_amount_after_discount_amount\":370.8,\"item_wise_tax_detail\":\"{\\\"01-0164-000\\\":[9,370.8]}\"},{\"docstatus\":0,\"doctype\":\"Sales Taxes and Charges\",\"name\":\"new-sales-taxes-and-charges-7\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"triotech.bhargav@gmail.com\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"cost_center\":\"Main - TMS\",\"account_currency\":\"INR\",\"dont_recompute_tax\":0,\"parent\":\"new-sales-invoice-1\",\"parentfield\":\"taxes\",\"parenttype\":\"Sales Invoice\",\"idx\":2,\"row_id\":\"\",\"account_head\":\"Output Tax SGST - TMS\",\"description\":\"Output Tax SGST\",\"rate\":0,\"tax_amount\":370.8,\"total\":4861.6,\"tax_amount_after_discount_amount\":370.8,\"base_tax_amount\":370.8,\"base_total\":4861.6,\"base_tax_amount_after_discount_amount\":370.8,\"item_wise_tax_detail\":\"{\\\"01-0164-000\\\":[9,370.8]}\"}],\"conversion_rate\":1,\"plc_conversion_rate\":1,\"company_tax_id\":\"29ABOPN5849D1Z5\",\"company_address\":\"TrioTech Manufacturing systems-Billing\",\"debit_to\":\"ACE DESIGNERS LIMITED PLANT2 - TMS\",\"company_address_display\":\"848/5 TrioTech Manufacturing Systems,4th cross East End, 1st Stage,  Peenya Industrial Estate,Bengaluru\\n,Karnataka, State Code: 29 Postal Code: 560058,India <b><font size=\\\"1\\\">GSTIN: 29ABOPN5849D1Z5</b></font><br>Email: triotech.bhargav@gmail.com<br>\",\"company_gstin\":\"29ABOPN5849D1Z5\",\"posting_time\":\"11:08:57\",\"base_net_total\":4120,\"net_total\":4120,\"base_total\":4120,\"total\":4120,\"total_qty\":10,\"rounding_adjustment\":0.4,\"grand_total\":4861.6,\"base_grand_total\":4861.6,\"total_taxes_and_charges\":741.6,\"base_total_taxes_and_charges\":741.6,\"base_rounding_adjustment\":0.4,\"rounded_total\":4862,\"base_rounded_total\":4862,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"total_advance\":0,\"write_off_amount\":0,\"paid_amount\":0,\"base_paid_amount\":0,\"payments\":[],\"change_amount\":0,\"base_change_amount\":0,\"outstanding_amount\":4862,\"amount_eligible_for_commission\":4120,\"total_commission\":0,\"tax_id\":\"29AABCA2364F1ZW\",\"customer_name\":\"ACE DESIGNERS LIMITED. PLANT2\",\"customer\":\"ACE DESIGNERS LIMITED. PLANT2\",\"due_date\":\"2023-10-03\",\"customer_address\":\"ACE DESIGNERS LIMITED. PLANT2-Billing\",\"billing_address_gstin\":\"29AABCA2364F1ZW\",\"gst_category\":\"Registered Regular\",\"address_display\":\"NO 533, 10TH MAIN ROAD,4TH PHASE, PEENYA INDL AREA,  BANGALORE - 560058,Bangalore\\n,Karnataka, State Code: 29 Postal Code: 560058,India <b><font size=\\\"1\\\">GSTIN: 29AABCA2364F1ZW</font></b><br>\",\"tax_category\":\"Sales (In-State)\",\"place_of_supply\":\"29-Karnataka\",\"taxes_and_charges\":\"In-state GST(Sales) - TMS\",\"language\":\"en-GB\",\"sales_team\":[],\"idx\":0,\"set_warehouse\":\"Finished Goods - TMS\",\"total_net_weight\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"other_charges_calculation\":\"<div class=\\\"tax-break-up\\\" style=\\\"overflow-x: auto;\\\">\\n\\t<table class=\\\"table table-bordered table-hover\\\">\\n\\t\\t<thead>\\n\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-left\\\">HSN/SAC</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Taxable Amount</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Output Tax CGST</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Output Tax SGST</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t</tr>\\n\\t\\t</thead>\\n\\t\\t<tbody>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>84669310</td>\\n\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t₹ 4,120.00\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(9.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t₹ 370.80\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(9.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t₹ 370.80\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t</tbody>\\n\\t</table>\\n</div>\",\"total_billing_hours\":0,\"only_include_allocated_payments\":0,\"base_write_off_amount\":0,\"loyalty_points\":0,\"loyalty_amount\":0,\"po_no\":\"3500271965\",\"po_date\":\"2023-09-15\",\"commission_rate\":0,\"distance\":0,\"timesheets\":[],\"pricing_rules\":[],\"packed_items\":[],\"advances\":[],\"payment_schedule\":[],\"__onload\":{\"load_after_mapping\":true,\"ignore_price_list\":true}}",
		"action": "Save"
	},
	"btn": {
		"jQuery3600182000945452412081": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 10544,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'GSTSettings' object has no attribute 'validate_gstin_status'"
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Your site's database schema is not as per the APP.
Run `bench migrate` after every pull or update to update the database schema.

https://frappeframework.com/docs/user/en/guides/deployment/migrations
https://frappeframework.com/docs/user/en/bench/reference/migrate

Hope this helps.

Regards,
Lakshit Jain

**Comment by bhargav007n** [comment]
thank you.
Yes, working normal after bench migrate.
