### ISSUE TITLE
"Bill of Entry" DocType no found.

### ISSUE THREAD

**Issue by HUMENTH** [resilient-tech/india-compliance#1097]
### Information about bug

I get an error when I try to install India Compliance on a new ERPNext instance.
It says "Bill of Entry" DocType no found.
If I uninstall and reinstall the "India_Compliance" app, the error goes away.
  

### Version

Frappe version :- 15.0.0-dev(version-15-beta)
ERPNext version :- 15.0.0-dev(version-15-beta)
India-Compliance :- 15.0.0-dev(version-15-beta)

### Relevant log output / Stack trace / Full Error Message.

```shell
App erpnext already installed

Installing india_compliance...
Installation for India Compliance failed due to an error. Please try re-installing the app or report the issue on https://github.com/resilient-tech/india-compliance/issues/new if not resolved.
An error occurred while installing india_compliance: Could not find DocType: Bill of Entry
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 306, in install_app
    frappe.get_attr(after_install)()
  File "apps/india_compliance/india_compliance/install.py", line 66, in after_install
    raise e
  File "apps/india_compliance/india_compliance/install.py", line 45, in after_install
    setup_audit_trail()
  File "apps/india_compliance/india_compliance/audit_trail/setup.py", line 15, in setup_fixtures
    create_property_setters_for_versioning()
  File "apps/india_compliance/india_compliance/audit_trail/setup.py", line 35, in create_property_setters_for_versioning
    property_setter.insert()
  File "apps/frappe/frappe/model/document.py", line 276, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 905, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 570, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 542, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 491, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find DocType: Bill of Entry
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
It's more related to improper installation. Migrate is required to ensure a doctype is created after installing the app.
Closing this as it's not an actual issue.
