### ISSUE TITLE
Purchase Reco Tool Display issue

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#1203]
### Information about bug

After OTP screen submit
No data is shown in the Reco tool

But the GST Inward Supply List is fetched.

Below are getting .. Whole document was refreshed and also Clear the cache as well. still getting the same error.

### Version

ERPNext: v14.45.3 (version-14)

Frappe Framework: v14.53.2 (version-14)

Frappe HR: v14.14.0 (version-14)

India Compliance: v14.18.1 (version-14)

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"addon_s_bom": "0.0.1",
	"addon_s_hr": "0.0.1",
	"addon_s_stocks": "0.0.1",
	"addons_boms": "0.0.1",
	"addons_buying": "0.0.1",
	"chat": "0.0.1",
	"erpnext": "14.45.3",
	"frappe": "14.53.2",
	"hrms": "14.14.0",
	"india_compliance": "14.18.1",
	"reports": "0.0.1",
	"sync_emp_checkin": "0.0.1"
}
```
### Route
```
Form/Purchase Reconciliation Tool/Purchase Reconciliation Tool
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 343, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1055, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 919, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1281, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1263, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 916, in fn
    return method_object(*args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py", line 58, in validate
    _Reconciler.reconcile(row["original"], row["amended"])
  File "apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py", line 748, in reconcile
    self.reconcile_for_rules(GSTIN_RULES, purchases, inward_supplies, category)
  File "apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py", line 764, in reconcile_for_rules
    self.reconcile_for_rule(
  File "apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py", line 800, in reconcile_for_rule
    inward_supplies[supplier_gstin].copy().items()
KeyError: ''

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"Purchase Reconciliation Tool\",\"owner\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"company\":\"Blisstering Electronics Private Limited\",\"include_ignored\":0,\"purchase_period\":\"Last Month\",\"inward_supply_period\":\"Last Month\",\"gst_return\":\"GSTR 2B\",\"is_modified\":0,\"doctype\":\"Purchase Reconciliation Tool\",\"company_gstin\":\"09AAGCB7154D1ZQ\",\"__unsaved\":true,\"purchase_from_date\":\"2023-09-01\",\"purchase_to_date\":\"2023-09-30\",\"inward_supply_from_date\":\"2023-09-01\",\"inward_supply_to_date\":\"2023-09-30\",\"reconciliation_data\":null}",
		"action": "Save"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "KeyError: ''"
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Looks like you seem to have purchase invoices with taxes but without supplier GSTIN. This is very unlikely, as we already have validation for this in place. Should be there for transactions from v13.

Can you confirm if this is the case?

**Comment by dineshpanchal93** [comment]
No, We have no transaction from v13.

New System Start from 1st April 2023 with v14.

**Comment by dineshpanchal93** [comment]
Only we have selected the Purchase Period and reconcile
below is the output.

<img width="1313" alt="Screenshot 2023-10-28 at 3 45 27 PM" src="https://github.com/resilient-tech/india-compliance/assets/21578167/2a20fde9-b5fb-4a78-82a2-88b0b7fbbe1c">

**Comment by vorasmit** [comment]
Do you have imports in the Bill of Entry? Probably Yes
Do you have GST Inward Supply with Category IMPG? Probably No.
![image](https://github.com/resilient-tech/india-compliance/assets/10496564/989c6891-f444-4f7f-a87a-95a81a1cb14f)


If so, this could be causing the issue. Can you confirm this for me, please?

**Comment by dineshpanchal93** [comment]
Yes, We have imports  in the Bill of Entry.

GST Inward Supply with Category IMPG? Yes- 

<img width="1316" alt="Screenshot 2023-10-28 at 4 22 30 PM" src="https://github.com/resilient-tech/india-compliance/assets/21578167/59793ccd-ea29-41d2-87c6-f9a2b8399c61">

**Comment by dineshpanchal93** [comment]
@vorasmit  

Thank you so much for the prompt support.
