### ISSUE TITLE
Purchase Reconciliation Error

### ISSUE THREAD

**Issue by jpettan** [resilient-tech/india-compliance#1226]
### App Versions
```
{
	"chat": "0.0.1",
	"erpnext": "14.45.1",
	"frappe": "14.53.1",
	"hrms": "14.14.0",
	"india_compliance": "14.17.3",
	"payments": "0.0.1"
}
```
### Route
```
Form/Purchase Reconciliation Tool/Purchase Reconciliation Tool
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 343, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1055, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 919, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1281, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1263, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 916, in fn
    return method_object(*args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py", line 58, in validate
    _Reconciler.reconcile(row["original"], row["amended"])
  File "apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py", line 739, in reconcile
    self.reconcile_for_rules(GSTIN_RULES, purchases, inward_supplies, category)
  File "apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py", line 755, in reconcile_for_rules
    self.reconcile_for_rule(
  File "apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py", line 778, in reconcile_for_rule
    summary_diff = self.get_summary_difference(
  File "apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py", line 825, in get_summary_difference
    summary.setdefault(doc.bill_date.month, 0)
AttributeError: 'NoneType' object has no attribute 'month'
Used purchase reconciliation tool. The tool downloaded the  documents. However when we try to reconcile, the following error is shown. Please resolve.





```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"Purchase Reconciliation Tool\",\"owner\":\"jithu.pettan@stergycleantech.com\",\"modified\":\"2023-10-27 20:42:18.479682\",\"modified_by\":\"jithu.pettan@stergycleantech.com\",\"docstatus\":0,\"idx\":\"0\",\"company\":\"Stergy Cleantech Private Limited\",\"include_ignored\":0,\"company_gstin\":\"32AAYCS8836K1ZG\",\"purchase_period\":\"Last Fiscal Year\",\"purchase_from_date\":\"2022-04-01\",\"purchase_to_date\":\"2023-03-31\",\"inward_supply_period\":\"Last Fiscal Year\",\"inward_supply_from_date\":\"2022-04-01\",\"inward_supply_to_date\":\"2023-03-31\",\"gst_return\":\"Both GSTR 2A & 2B\",\"is_modified\":0,\"reconciliation_data\":null,\"doctype\":\"Purchase Reconciliation Tool\",\"__last_sync_on\":\"2023-10-31T15:22:01.250Z\",\"__unsaved\":true}",
		"action": "Save"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute 'month'"
}
```

**Comment by vorasmit** [comment]
This is fixed here and released in v18.0
https://github.com/resilient-tech/india-compliance/pull/1178
