### ISSUE TITLE
Can't install on my self-hosted docker instance.

### ISSUE THREAD

**Issue by stockarea** [resilient-tech/india-compliance#1244]
### Information about bug

I tried pulling branch version-14 as per the docs but while building it gives out error and does not build perfectly.

    
    
Can anyone help what could be the reason for this?

### Version

ERPNext: v15.0.0

Frappe Framework: v15.0.2

### Relevant log output / Stack trace / Full Error Message.

```shell
yarn run v1.22.19
$ node esbuild --production --apps india_compliance --run-build-command
✘ [ERROR] No matching export in "node_modules/vue-router/dist/vue-router.mjs" for import "default"

    ../india_compliance/india_compliance/public/js/india_compliance_account/router.js:1:7:
      1 │ import VueRouter from "vue-router";
        ╵        ~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"

    ../india_compliance/india_compliance/public/js/india_compliance_account/india_compliance_account.bundle.js:1:7:
      1 │ import Vue from "vue";
        ╵        ~~~

✘ [ERROR] No matching export in "node_modules/vue-router/dist/vue-router.mjs" for import "default"

    ../india_compliance/india_compliance/public/js/india_compliance_account/india_compliance_account.bundle.js:2:7:
      2 │ import VueRouter from "vue-router";
        ╵        ~~~~~~~~~

✘ [ERROR] [plugin frappe-vue-style] Cannot read properties of undefined (reading 'outputs')

    /home/frappe/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:10:41:
      10 │       let files = get_files(result.metafile.outputs);
         ╵                                             ^

    at /home/frappe/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:10:42
    at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1052:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  This error came from the "onEnd" callback registered here:

    /home/frappe/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:9:8:
      9 │     build.onEnd((result) => {
        ╵           ~~~~~

    at setup (/home/frappe/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:9:9)
    at handlePlugins (/home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:855:23)

 ERROR  There were some problems during build

Error: Build failed with 4 errors:
../india_compliance/india_compliance/public/js/india_compliance_account/india_compliance_account.bundle.js:1:7: ERROR: No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
../india_compliance/india_compliance/public/js/india_compliance_account/india_compliance_account.bundle.js:2:7: ERROR: No matching export in "node_modules/vue-router/dist/vue-router.mjs" for import "default"
../india_compliance/india_compliance/public/js/india_compliance_account/router.js:1:7: ERROR: No matching export in "node_modules/vue-router/dist/vue-router.mjs" for import "default"
/home/frappe/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:10:41: ERROR: [plugin: frappe-vue-style] Cannot read properties of undefined (reading 'outputs')
    at failureErrorWithLog (/home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1624:15)
    at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1266:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
   
Terminated
    ```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
This is not the right forum for help. The commands for installation suggested by us are just for manual installation and not docker.

You can look for help in the discussion forum. There are similar articles already available and experts with docker could guide you better.
https://discuss.frappe.io/

You can refer to docs here on how to add custom apps:
https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md

**Comment by stockarea** [comment]
@vorasmit I am installing inside a docker container and running this command inside a docker container. I can't find how can I install it on ERPnext running on docker since they recommend to run ERPnext on docker on production instance.

**Comment by stockarea** [comment]
@vorasmit Also could it be that I am installing on ERPNext v15 for which this project is not updated?
