### ISSUE TITLE
API access is not available or user expiry Duration is less than or equal to auth token expiry duration

### ISSUE THREAD

**Issue by dhawal-mahajan** [resilient-tech/india-compliance#1292]
### Information about bug

ERPNext: v14.47.4 (version-14)

Frappe Framework: v14.54.1 (version-14)

India Compliance: v14.19.2 (version-14)

On fetching GSTR2A/2B from Purchase Reconciliation Tool Receive the error

![image](https://github.com/resilient-tech/india-compliance/assets/89780161/5de83dd8-b153-451e-9f2c-57a687d20370)

All other features like Einvoice, E-way bill work correctly

### Version

ERPNext: v14.47.4 (version-14)

Frappe Framework: v14.54.1 (version-14)

India Compliance: v14.19.2 (version-14)

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback : 
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 323, in run_doc_method
    response = doc.run_method(method, **args)
  File "apps/frappe/frappe/model/document.py", line 919, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1281, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1263, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 916, in fn
    return method_object(*args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py", line 88, in download_gstr_2a
    return download_gstr_2a(self.company_gstin, periods, otp)
  File "apps/india_compliance/india_compliance/gst_india/utils/gstr/__init__.py", line 87, in download_gstr_2a
    response = api.get_data(action, return_period, otp)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 377, in get_data
    return self.get(
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 270, in get
    return self._request("get", action, return_period, params, endpoint, None, otp)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 248, in _request
    response = self.autheticate_with_otp(otp=otp)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 101, in autheticate_with_otp
    return self.request_otp()
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 73, in request_otp
    response = super().post(
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 81, in post
    return self._make_request("POST", *args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 161, in _make_request
    raise e
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 156, in _make_request
    response_json = self.process_response(response_json)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 279, in process_response
    self.handle_error_response(response)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 308, in handle_error_response
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 534, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 502, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 451, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: API access is not available or user expiry Duration is less than or equal to auth token expiry duration
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
https://docs.indiacompliance.app/docs/miscellaneous/purchase_reconciliation_tool#configuration

Is API Access Enabled in GST Portal?

**Comment by dhawal-mahajan** [comment]
@vorasmit API Access was enabled. I was using E Invoice Portal Login Credentials for Reports as well.  Replaced it with GST Portal User Id
