### ISSUE TITLE
Installation Error: Could Not Find Bill Of Entry

### ISSUE THREAD

**Issue by stockarea** [resilient-tech/india-compliance#1368]
### Information about bug

App erpnext already installed

Installing india_compliance...
Installation for India Compliance failed due to an error. Please try re-installing the app or report the issue on https://github.com/resilient-tech/india-compliance/issues/new if not resolved.
An error occurred while installing india_compliance: Could not find DocType: Bill of Entry
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 306, in install_app
    frappe.get_attr(after_install)()
  File "apps/india_compliance/india_compliance/install.py", line 68, in after_install
    raise e
  File "apps/india_compliance/india_compliance/install.py", line 47, in after_install
    setup_audit_trail()
  File "apps/india_compliance/india_compliance/audit_trail/setup.py", line 15, in setup_fixtures
    create_property_setters_for_versioning()
  File "apps/india_compliance/india_compliance/audit_trail/setup.py", line 35, in create_property_setters_for_versioning
    property_setter.insert()
  File "apps/frappe/frappe/model/document.py", line 278, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 918, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 577, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 549, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 500, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find DocType: Bill of Entry

### Version

Frappe version : 15
ERPnext Version : 15
India Compliance : 15

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Hi,

This looks like an installation Issue.

Installation of the app should never fail because of missing doctype (Bill of Entry), as it's already part of the test script.

Can you try again on a new instance and check if the error persists? Are you using frappe cloud? If not, can you try it on frappe cloud?
