### ISSUE TITLE
GSTR-1 Download as Json

### ISSUE THREAD

**Issue by jecinthamary** [resilient-tech/india-compliance#1381]
### Information about bug

On clicking Download as JSON in the GSTR-1 report, it shows a console traceback error.

TypeError: india_compliance.trigger_file_download is not a function
    at Object.callback (gstr_1.js:150:22)
    at Object.e [as success_callback] (request.js:85:16)
    at 200 (request.js:128:34)
    at Object.<anonymous> (request.js:294:6)
    at V (jquery.js:3500:31)
    at Object.fireWith [as resolveWith] (jquery.js:3630:7)
    at S0 (jquery.js:9796:14)
    at XMLHttpRequest.<anonymous> (jquery.js:10057:9)

india_compliance/gst_india/report/gstr_1/gstr_1.js#L110
	india_compliance.trigger_file_download(JSON.stringify(r.message.data), r.message.file_name);

### Version

Frappe Framework: v14.55.1 (version-14)
ERPNext: v14.49.0 (version-14)
India Compliance: v14.19.4 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Is it self-hosted? Most likely bench is not built properly. Running following command in bench directory should help
```
bench --site [SITENAME] build --app india_compliance
```

**Comment by jecinthamary** [comment]
@vorasmit Thanks
