### ISSUE TITLE
API Request Failed: User Password has expired. Contact Support.

### ISSUE THREAD

**Issue by Govind-Jangid** [resilient-tech/india-compliance#1593]
### Information about bug

Showing API Request Failed User Password has expired. Contact Support., while adding new Customer/Supplier using GSTIN - Autofill party information by entering their GSTIN on both sites @FrappeCloud and @SelfHosted Sites, at self hosted site we have Available Credits 9,989.

### Version

Showing error on both v14 and v15

### Relevant log output / Stack trace / Full Error Message.

```shell
desk.bundle.RZW2WOV4.js:sourcemap:446 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1620, in call
    return fn(*args, **newargs)
  File "apps/india_compliance/india_compliance/gst_india/utils/gstin_info.py", line 30, in get_gstin_info
    return _get_gstin_info(gstin, throw_error=throw_error)
  File "apps/india_compliance/india_compliance/gst_india/utils/gstin_info.py", line 47, in _get_gstin_info
    raise exc
  File "apps/india_compliance/india_compliance/gst_india/utils/gstin_info.py", line 39, in _get_gstin_info
    response = PublicAPI().get_gstin_info(gstin)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/public.py", line 21, in get_gstin_info
    response = self.get("search", params={"action": "TP", "gstin": gstin})
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 78, in get
    return self._make_request("GET", *args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 161, in _make_request
    raise e
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 156, in _make_request
    response_json = self.process_response(response_json)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 180, in process_response
    self.handle_error_response(response)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 194, in handle_error_response
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 540, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 508, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 454, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: User Password has expired. Contact Support.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Can you please share the integration request log? This issue is from the e-Invoice or GST portal. It's got nothing to do with available credits.

Also, I just checked (autofill API) and it seems to be working for me now. Can you check if it was a temporary issue? Still do share the Integration Request Log for our reference.

**Comment by Govind-Jangid** [comment]
Now working fine.
Thanks
