### ISSUE TITLE
AttributeError: 'AccountsSettings' object has no attribute 'enable_audit_trail'

### ISSUE THREAD

**Issue by mohsinalimat** [resilient-tech/india-compliance#1596]
### Route
```
Form/Accounts Settings/Accounts Settings
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 344, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1058, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 922, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1284, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1268, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/audit_trail/overrides/accounts_settings.py", line 9, in validate
    validate_delete_linked_ledger_entries(doc)
  File "apps/india_compliance/india_compliance/audit_trail/overrides/accounts_settings.py", line 25, in validate_delete_linked_ledger_entries
    if doc.enable_audit_trail and doc.delete_linked_ledger_entries:
AttributeError: 'AccountsSettings' object has no attribute 'enable_audit_trail'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"Accounts Settings\",\"owner\":\"Administrator\",\"creation\":\"2022-11-22 10:46:15.974459\",\"modified\":\"2024-01-13 18:23:14.039647\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":\"0\",\"custom_enable_audit_trail\":1,\"unlink_payment_on_cancellation_of_invoice\":1,\"unlink_advance_payment_on_cancelation_of_order\":1,\"delete_linked_ledger_entries\":0,\"check_supplier_invoice_uniqueness\":1,\"automatically_fetch_payment_terms\":1,\"enable_common_party_accounting\":1,\"allow_multi_currency_invoices_against_single_party_account\":0,\"merge_similar_account_heads\":0,\"use_custom_cash_flow\":0,\"book_deferred_entries_based_on\":\"Days\",\"automatically_process_deferred_accounting_entry\":1,\"book_deferred_entries_via_journal_entry\":0,\"submit_journal_entries\":0,\"determine_address_tax_category_from\":\"Billing Address\",\"add_taxes_from_item_tax_template\":0,\"book_tax_discount_loss\":0,\"show_inclusive_tax_in_print\":1,\"show_taxes_as_table_in_print\":0,\"show_payment_schedule_in_print\":1,\"allow_stale\":1,\"auto_reconcile_payments\":0,\"stale_days\":1,\"over_billing_allowance\":100,\"role_allowed_to_over_bill\":\"Sales User\",\"make_payment_via_journal_entry\":0,\"post_change_gl_entries\":1,\"book_asset_depreciation_entry_automatically\":1,\"ignore_account_closing_balance\":0,\"enable_party_matching\":0,\"enable_fuzzy_matching\":0,\"show_balance_in_coa\":0,\"general_ledger_remarks_length\":0,\"receivable_payable_remarks_length\":0,\"doctype\":\"Accounts Settings\",\"__last_sync_on\":\"2024-01-13T13:06:18.055Z\",\"__unsaved\":1}",
		"action": "Save"
	},
	"btn": {
		"jQuery3600136844536264026041": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 909,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'AccountsSettings' object has no attribute 'enable_audit_trail'"
}
```

### App Versions
```
{
	"erpnext": "14.58.1",
	"frappe": "14.62.1",
	"hrms": "14.21.0",
	"india_compliance": "14.23.1",
	"payments": "0.0.1"
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
This is linked to https://github.com/resilient-tech/india-compliance/issues/1597, let's continue the discussion there.

**Comment by mohsinalimat** [comment]
Issue solved with below link

@sagarvora thanks a lot.

https://discuss.frappe.io/t/invalid-field-name-enable-audit-trail/115831/2?u=mohsininspire
