### ISSUE TITLE
Unable to Create Variants for Item

### ISSUE THREAD

**Issue by chechani** [resilient-tech/india-compliance#1640]
### Information about bug

we are unable to create variant as we have installed the India Compliacne APP

refer the attached video

https://github.com/resilient-tech/india-compliance/assets/6291292/04a40406-6fa0-46d3-bb9b-12ef5c5381f6

### Version

ERPNext: v15.10.7 (version-15)

Frappe Framework: v15.11.0 (version-15)

India Compliance: v15.5.0 (version-15)

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/item_variant.py", line 237, in enqueue_multiple_variant_creation
    return create_multiple_variants(item, args)
  File "apps/erpnext/erpnext/controllers/item_variant.py", line 258, in create_multiple_variants
    variant.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1085, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 954, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1320, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 9, in validate
    validate_hsn_code(doc)
  File "apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 18, in validate_hsn_code
    _validate_hsn_code(doc.gst_hsn_code)
  File "apps/india_compliance/india_compliance/gst_india/doctype/gst_hsn_code/gst_hsn_code.py", line 56, in validate_hsn_code
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 578, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 550, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 501, in _raise_exception
    raise exc
frappe.exceptions.MandatoryError: HSN/SAC Code is required. Please enter a valid HSN/SAC code.
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishakhdesai** [comment]
![image](https://github.com/resilient-tech/india-compliance/assets/78500008/9154b880-f75c-4490-b7a9-8955f2cce877)


It appears that the field `gst_hsn_code` may not be configured in the **Item Variant Settings** on your site for some reason. To address this issue, kindly add this field to the settings, and this action should resolve the issue you are experiencing.

**Comment by chechani** [comment]
This worked..thanks
