### ISSUE TITLE
Error while placing an order on Webshop

### ISSUE THREAD

**Issue by simran-baliyan** [resilient-tech/india-compliance#1660]
### Information about bug

When we try to place an order on Webshop, it throws an error.
Kindly fix it.

### Version

ERPNext: v15.11.1 (version-15)
Frappe Framework: v15.12.0 (version-15)
India Compliance: v15.5.1 (version-15)
![Screenshot 2024-02-03 221104](https://github.com/resilient-tech/india-compliance/assets/158838687/eda2292b-c701-4d9b-8787-78ee426bf21c)
![Screenshot 2024-02-03 214723](https://github.com/resilient-tech/india-compliance/assets/158838687/c824a966-1d2f-48b2-a38a-654fd8fa480c)
![Screenshot 2024-02-03 215702](https://github.com/resilient-tech/india-compliance/assets/158838687/51e10976-522a-42d3-ba85-0e32a88e314d)
![Screenshot 2024-02-03 221916](https://github.com/resilient-tech/india-compliance/assets/158838687/3c2a7f98-19a2-4226-83a2-fe8eca58733d)

We are a regular payer , it shows composition.

### Relevant log output / Stack trace / Full Error Message.

*No response*

### Code of Conduct

* [X] I agree to follow this project's Code of Conduct

**Comment by simran-baliyan** [comment]
@vorasmit Traceback (most recent call last):
  File "apps/frappe/frappe/[app.py](https://app.py/)", line 106, in application
    frappe.handler.handle()
  File "apps/frappe/frappe/[handler.py](https://handler.py/)", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/[handler.py](https://handler.py/)", line 85, in execute_cmd
    return [frappe.call](https://frappe.call/)(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1684, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_[validations.py](https://validations.py/)", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/webshop/webshop/webshop/shopping_cart/[cart.py](https://cart.py/)", line 135, in place_order
    sales_order.insert()
  File "apps/frappe/frappe/model/[document.py](https://document.py/)", line 286, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/[document.py](https://document.py/)", line 1085, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/[document.py](https://document.py/)", line 954, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/[document.py](https://document.py/)", line 1320, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/[document.py](https://document.py/)", line 1304, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/[transaction.py](https://transaction.py/)", line 1309, in validate_transaction
    valid_accounts = validate_gst_accounts(doc, is_sales_transaction) or ()
  File "apps/india_compliance/india_compliance/gst_india/overrides/[transaction.py](https://transaction.py/)", line 344, in validate_gst_accounts
    _throw(
  File "apps/india_compliance/india_compliance/gst_india/overrides/[transaction.py](https://transaction.py/)", line 228, in _throw
    frappe.throw(message, title=title or _("Invalid GST Account"))
  File "apps/frappe/frappe/__init__.py", line 578, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 550, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 501, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Row #1: Cannot charge IGST for intra-state supplies

**Comment by simran-baliyan** [comment]
@resilient-tech ?

**Comment by vorasmit** [comment]
This looks more likely an issue from the webshop app or your configurations.
A validation error is raised as an incorrect tax template is used.

**Comment by vorasmit** [comment]
Looks like these issues are fixed in webshop app
