### ISSUE TITLE
India Compliance app error while creating workorder against Production Plan

### ISSUE THREAD

**Issue by BHAGYASHRIMHASKE** [resilient-tech/india-compliance#1821]
### Information about bug

India Compliance app error while creating workorder against Production Plan

<img width="591" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/138584686/bfcfdd1c-7ae9-4ba1-acbf-f85f89e9e7f1">

### Version

<img width="158" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/138584686/ef1374b9-b60a-456a-9d34-feb66c414a29">

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.12.2",
	"frappe": "15.13.0",
	"hrms": "15.11.0",
	"india_compliance": "15.5.1",
	"payments": "0.0.1",
	"print_designer": "1.0.0"
}
```
### Route
```
Form/Production Plan/MFG-PP-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 326, in run_doc_method
    response = doc.run_method(method)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 940, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1300, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1282, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 937, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/manufacturing/doctype/production_plan/production_plan.py", line 677, in make_work_order
    self.make_subcontracted_purchase_order(subcontracted_po, po_list)
  File "apps/erpnext/erpnext/manufacturing/doctype/production_plan/production_plan.py", line 773, in make_subcontracted_purchase_order
    po.insert()
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1063, in run_before_save_methods
    self.run_method("before_validate")
  File "apps/frappe/frappe/model/document.py", line 940, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1300, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1284, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 1314, in before_validate
    set_reverse_charge_as_per_gst_settings(doc)
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 1223, in set_reverse_charge_as_per_gst_settings
    or doc.grand_total <= gst_settings.rcm_threshold
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'float'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"docs": "{\"name\":\"MFG-PP-2024-00001\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":0,\"naming_series\":\"MFG-PP-.YYYY.-\",\"company\":\"AUTOMATIC ELECTRIC LIMITED\",\"get_items_from\":\"Sales Order\",\"posting_date\":\"2024-03-06\",\"item_code\":\"Lighting Transformer 25KVA\",\"sales_order_status\":\"\",\"combine_items\":0,\"combine_sub_items\":1,\"skip_available_sub_assembly_item\":0,\"include_non_stock_items\":1,\"include_subcontracted_items\":1,\"consider_minimum_order_qty\":0,\"include_safety_stock\":1,\"ignore_existing_ordered_qty\":1,\"for_warehouse\":\"Power System Division-96 RM - AEL\",\"total_planned_qty\":1,\"total_produced_qty\":0,\"status\":\"Submitted\",\"doctype\":\"Production Plan\",\"sales_orders\":[{\"name\":\"1829f3fcf4\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":1,\"sales_order\":\"SAL-ORD-2024-00019\",\"sales_order_date\":\"2024-03-06\",\"customer\":\"ENPRO INDUSTRIAL AUTOMATION PVT LTD\",\"grand_total\":590000,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"sales_orders\",\"parenttype\":\"Production Plan\",\"doctype\":\"Production Plan Sales Order\"}],\"sub_assembly_items\":[{\"name\":\"7dfe277c36\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":1,\"production_item\":\"Lighting Transformer 25KVA Copper Winding\",\"item_name\":\"Lighting Transformer 25KVA Copper Winding\",\"fg_warehouse\":\"Power System Division-96 FG - AEL\",\"parent_item_code\":\"Lighting Transformer 25KVA\",\"schedule_date\":\"2024-03-06 20:03:45.260170\",\"qty\":1,\"bom_no\":\"BOM-Lighting Transformer 25KVA Copper Winding-001\",\"bom_level\":0,\"type_of_manufacturing\":\"In House\",\"wo_produced_qty\":0,\"production_plan_item\":\"bc29bae72c\",\"received_qty\":0,\"indent\":0,\"uom\":\"Nos\",\"stock_uom\":\"Nos\",\"description\":\"Lighting Transformer 25KVA Copper Winding\",\"actual_qty\":0,\"projected_qty\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"sub_assembly_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Production Plan Sub Assembly Item\"},{\"name\":\"2fdf4b2851\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":2,\"production_item\":\"Lighting Transformer 25KVA Stack\",\"item_name\":\"Lighting Transformer 25KVA Stack\",\"fg_warehouse\":\"Power System Division-96 FG - AEL\",\"parent_item_code\":\"Lighting Transformer 25KVA\",\"schedule_date\":\"2024-03-06 20:03:45.260170\",\"qty\":1,\"bom_no\":\"BOM-Lighting Transformer 25KVA Stack-001\",\"bom_level\":0,\"type_of_manufacturing\":\"In House\",\"wo_produced_qty\":0,\"production_plan_item\":\"bc29bae72c\",\"received_qty\":0,\"indent\":0,\"uom\":\"Nos\",\"stock_uom\":\"Nos\",\"description\":\"Lighting Transformer 25KVA Stack\",\"actual_qty\":0,\"projected_qty\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"sub_assembly_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Production Plan Sub Assembly Item\"},{\"name\":\"0b8db5d1f1\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":3,\"production_item\":\"Lighting Transformer 25KVA Painting\",\"item_name\":\"Lighting Transformer 25KVA Painting\",\"fg_warehouse\":\"Power System Division-96 FG - AEL\",\"parent_item_code\":\"Lighting Transformer 25KVA\",\"schedule_date\":\"2024-03-06 20:03:45.260170\",\"qty\":1,\"bom_no\":\"BOM-Lighting Transformer 25KVA Painting-001\",\"bom_level\":0,\"type_of_manufacturing\":\"Subcontract\",\"supplier\":\"Painting Subcontractor\",\"wo_produced_qty\":0,\"production_plan_item\":\"bc29bae72c\",\"received_qty\":0,\"indent\":0,\"uom\":\"Nos\",\"stock_uom\":\"Nos\",\"description\":\"Lighting Transformer 25KVA Painting\",\"actual_qty\":0,\"projected_qty\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"sub_assembly_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Production Plan Sub Assembly Item\"},{\"name\":\"0e577415b7\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":4,\"production_item\":\"Lighting Transformer 25KVA Fabrication\",\"item_name\":\"Lighting Transformer 25KVA Fabrication\",\"fg_warehouse\":\"Power System Division-96 FG - AEL\",\"parent_item_code\":\"Lighting Transformer 25KVA Painting\",\"schedule_date\":\"2024-03-06 20:03:45.260170\",\"qty\":1,\"bom_no\":\"BOM-Lighting Transformer 25KVA Fabrication-001\",\"bom_level\":1,\"type_of_manufacturing\":\"Subcontract\",\"supplier\":\"Fabrication Subcontractor\",\"wo_produced_qty\":0,\"production_plan_item\":\"bc29bae72c\",\"received_qty\":0,\"indent\":1,\"uom\":\"Nos\",\"stock_uom\":\"Nos\",\"description\":\"Lighting Transformer 25KVA Fabrication\",\"actual_qty\":0,\"projected_qty\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"sub_assembly_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Production Plan Sub Assembly Item\"}],\"material_requests\":[],\"mr_items\":[{\"name\":\"e71ebddf21\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":1,\"item_code\":\"Cello Tape\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Cello Tape \",\"material_request_type\":\"Purchase\",\"quantity\":1,\"required_bom_qty\":1,\"uom\":\"Nos\",\"conversion_factor\":1,\"description\":\"Cello Tape \",\"min_order_qty\":0,\"actual_qty\":1,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":4,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"438051ad61\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":2,\"item_code\":\"Copper  10SWG\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Copper  10SWG\",\"material_request_type\":\"Purchase\",\"quantity\":25,\"required_bom_qty\":25,\"uom\":\"Kg\",\"conversion_factor\":1,\"description\":\"Copper  10SWG\",\"min_order_qty\":0,\"actual_qty\":25,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":100,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"a329245d9d\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":3,\"item_code\":\"Copper cable\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Copper cable\",\"material_request_type\":\"Purchase\",\"quantity\":15,\"required_bom_qty\":15,\"uom\":\"Meter\",\"conversion_factor\":1,\"description\":\"Copper cable\",\"min_order_qty\":0,\"actual_qty\":15,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":75,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"006f6f8384\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":4,\"item_code\":\"Copper Strip 7/2\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Copper Strip 7/2 \",\"material_request_type\":\"Purchase\",\"quantity\":20,\"required_bom_qty\":20,\"uom\":\"Kg\",\"conversion_factor\":1,\"description\":\"Copper Strip 7/2 \",\"min_order_qty\":0,\"actual_qty\":20,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":80,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"272843e2a0\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":5,\"item_code\":\"Cotton Tape\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Cotton Tape\",\"material_request_type\":\"Purchase\",\"quantity\":1,\"required_bom_qty\":1,\"uom\":\"Nos\",\"conversion_factor\":1,\"description\":\"Cotton Tape\",\"min_order_qty\":0,\"actual_qty\":1,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":4,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"ed075f80be\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":6,\"item_code\":\"CRGO\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"CRGO\",\"material_request_type\":\"Purchase\",\"quantity\":108,\"required_bom_qty\":108,\"uom\":\"Kg\",\"conversion_factor\":1,\"description\":\"CRGO\",\"min_order_qty\":0,\"actual_qty\":108,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":432,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"14e8445825\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":7,\"item_code\":\"Fiber Glass Cloth\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Fiber Glass Cloth\",\"material_request_type\":\"Purchase\",\"quantity\":10,\"required_bom_qty\":10,\"uom\":\"Meter\",\"conversion_factor\":1,\"description\":\"Fiber Glass Cloth\",\"min_order_qty\":0,\"actual_qty\":10,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":40,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"4dfe524b48\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":8,\"item_code\":\"Fiber Glass Sheet\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Fiber Glass Sheet\",\"material_request_type\":\"Purchase\",\"quantity\":3,\"required_bom_qty\":3,\"uom\":\"Nos\",\"conversion_factor\":1,\"description\":\"Fiber Glass Sheet\",\"min_order_qty\":0,\"actual_qty\":3,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":15,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"fa87f9dc36\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":9,\"item_code\":\"Main Lables\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Main Lables\",\"material_request_type\":\"Purchase\",\"quantity\":2,\"required_bom_qty\":2,\"uom\":\"Nos\",\"conversion_factor\":1,\"description\":\"Main Lables\",\"min_order_qty\":0,\"actual_qty\":2,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":10,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"cf513ee5b6\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":10,\"item_code\":\"Momex Paper\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Momex Paper\",\"material_request_type\":\"Purchase\",\"quantity\":1.5,\"required_bom_qty\":1.5,\"uom\":\"Meter\",\"conversion_factor\":1,\"description\":\"Momex Paper\",\"min_order_qty\":0,\"actual_qty\":1.5,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":6,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"8d7468f96a\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":11,\"item_code\":\"MS /CRCA Sheet\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"MS /CRCA Sheet\",\"material_request_type\":\"Purchase\",\"quantity\":121,\"required_bom_qty\":121,\"uom\":\"Kg\",\"conversion_factor\":1,\"description\":\"MS /CRCA Sheet\",\"min_order_qty\":0,\"actual_qty\":121,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":484,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"f2009e8e20\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":12,\"item_code\":\"MS Channael 75/40/6\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"MS Channael 75/40/6\",\"material_request_type\":\"Purchase\",\"quantity\":25,\"required_bom_qty\":25,\"uom\":\"Kg\",\"conversion_factor\":1,\"description\":\"MS Channael 75/40/6\",\"min_order_qty\":0,\"actual_qty\":25,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":100,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"d4e72f35e8\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":13,\"item_code\":\"RAL 7032/7035\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"RAL 7032/7035\",\"material_request_type\":\"Purchase\",\"quantity\":10,\"required_bom_qty\":10,\"uom\":\"Kg\",\"conversion_factor\":1,\"description\":\"RAL 7032/7035\",\"min_order_qty\":0,\"actual_qty\":10,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":40,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"cfe3ecc2ff\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":14,\"item_code\":\"Tap Selector switch\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Tap Selector switch\",\"material_request_type\":\"Purchase\",\"quantity\":1,\"required_bom_qty\":1,\"uom\":\"Nos\",\"conversion_factor\":1,\"description\":\"Tap Selector switch\",\"min_order_qty\":0,\"actual_qty\":1,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":5,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"e0f8e4d572\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":15,\"item_code\":\"Teminal Labels\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Teminal Labels\",\"material_request_type\":\"Purchase\",\"quantity\":14,\"required_bom_qty\":14,\"uom\":\"Nos\",\"conversion_factor\":1,\"description\":\"Teminal Labels\",\"min_order_qty\":0,\"actual_qty\":14,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":70,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"25ffa477a2\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":16,\"item_code\":\"Tempreature Scanner\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Tempreature Scanner\",\"material_request_type\":\"Purchase\",\"quantity\":6,\"required_bom_qty\":6,\"uom\":\"Nos\",\"conversion_factor\":1,\"description\":\"Tempreature Scanner\",\"min_order_qty\":0,\"actual_qty\":6,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":30,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"630f39b56d\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":17,\"item_code\":\"Terminal Stud\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Terminal Stud\",\"material_request_type\":\"Purchase\",\"quantity\":8,\"required_bom_qty\":8,\"uom\":\"Nos\",\"conversion_factor\":1,\"description\":\"Terminal Stud\",\"min_order_qty\":0,\"actual_qty\":8,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":40,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"},{\"name\":\"1bd06505ca\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":18,\"item_code\":\"Wooden\",\"warehouse\":\"Power System Division-96 RM - AEL\",\"item_name\":\"Wooden\",\"material_request_type\":\"Purchase\",\"quantity\":25,\"required_bom_qty\":25,\"uom\":\"Kg\",\"conversion_factor\":1,\"description\":\"Wooden\",\"min_order_qty\":0,\"actual_qty\":25,\"requested_qty\":0,\"reserved_qty_for_production\":0,\"ordered_qty\":0,\"projected_qty\":125,\"safety_stock\":0,\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"mr_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Material Request Plan Item\"}],\"warehouses\":[],\"po_items\":[{\"name\":\"bc29bae72c\",\"owner\":\"rm@test.com\",\"creation\":\"2024-03-06 20:08:19.664199\",\"modified\":\"2024-03-06 20:08:29.903435\",\"modified_by\":\"rm@test.com\",\"docstatus\":1,\"idx\":1,\"include_exploded_items\":1,\"item_code\":\"Lighting Transformer 25KVA\",\"bom_no\":\"BOM-Lighting Transformer 25KVA-002\",\"planned_qty\":1,\"warehouse\":\"Power System Division-96 FG - AEL\",\"planned_start_date\":\"2024-03-06 20:03:45.260170\",\"pending_qty\":1,\"ordered_qty\":0,\"description\":\"Lighting Transformer 25KVA\",\"stock_uom\":\"Nos\",\"produced_qty\":0,\"sales_order\":\"SAL-ORD-2024-00019\",\"sales_order_item\":\"dc74468954\",\"temporary_name\":\"bc29bae72c\",\"parent\":\"MFG-PP-2024-00001\",\"parentfield\":\"po_items\",\"parenttype\":\"Production Plan\",\"doctype\":\"Production Plan Item\"}],\"prod_plan_references\":[],\"__last_sync_on\":\"2024-03-06T14:38:38.015Z\"}",
		"method": "make_work_order"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/run_doc_method",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: '<=' not supported between instances of 'NoneType' and 'float'",
	"exc_type": "TypeError",
	"_exc_source": "india_compliance (app)"
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajamuppidi** [comment]
What command did you use to install the India-complaint app ??
