### ISSUE TITLE
Unable to install India-compliance in the Bench version 15 , Error during migrate 

### ISSUE THREAD

**Issue by rajamuppidi** [resilient-tech/india-compliance#1831]
### Information about bug

I tried installing the India compliance app in my ERPNext self-hosted

Installed using 

bench get-app --branch version-15 https://github.com/resilient-tech/india-compliance.git

bench --site frontend install-app india_compliance 

bench migrate --skip-failing

I have installed both in frontend and backend containers during migration I am getting the error, and even the dock is not working. Now completely, my site is broken, 

I would appreciate your help with this. I followed the official documentation and need clarification on why this error occurred. 

In the website i am getting the bellow error 

Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 241, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'frappe.core.doctype.gst_settings'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/www/app.py", line 29, in get_context
    boot = frappe.sessions.get()
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/sessions.py", line 143, in get
    bootinfo = get_bootinfo()
               ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/boot.py", line 86, in get_bootinfo
    frappe.get_attr(method)(bootinfo)
  File "apps/india_compliance/india_compliance/boot.py", line 18, in set_bootinfo
    gst_settings = frappe.get_cached_doc("GST Settings").as_dict()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/base_document.py", line 69, in get_controller
    site_controllers[doctype] = import_controller(doctype)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    module = load_doctype_module(doctype, module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for GST Settings, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.gst_settings'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 524, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
    data = self.run_pymodule_method("get_context")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 225, in run_pymodule_method
    return method(self.context)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/www/app.py", line 31, in get_context
    raise frappe.SessionBootFailed from e
frappe.exceptions.SessionBootFailed

### Version

ERPNext Version - 15.6

### Relevant log output / Stack trace / Full Error Message.

```shell
Updating DocTypes for india_compliance: [======                                  ] 15%Queued rebuilding of search index for frontend

Traceback with variables (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
      mod_name = 'frappe.utils.bench_helper'
      alter_argv = True
      mod_spec = ModuleSpec(name='frappe.utils.bench_helper', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f23e69cd990>, origin='/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py')
      code = <code object <module> at 0x559fab7fa8b0, file "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 1>
      main_globals = {'__name__': '__main__', '__doc__': None, '__package__': 'frappe.utils', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7f23e69cd990>, '__spec__': ModuleSpec(name='frappe.utils.bench_helper', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f23e69cd990>, origin='/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py'), '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py', '__cached__': '/home/frappe/frappe-bench/apps/frappe/frappe/utils/__pycache__/bench_helper.cpython-311.pyc', 'importlib': <module 'importlib' from '/usr/local/lib/python3.11/importlib/__init__.py'>, 'json': <module 'json' from '/usr/local/lib/python3.11/json/__init__.py'>, 'os': <module 'os' (frozen)>, 'traceback': <module 'traceback' from '/usr/local/lib/python3.11/traceback.py'>, 'warnings': <module 'warnings' from '/usr/local/lib/python3.11/warnings.py'>, 'Path': <cl...
  File "<frozen runpy>", line 88, in _run_code
      code = <code object <module> at 0x559fab7fa8b0, file "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 1>
      run_globals = {'__name__': '__main__', '__doc__': None, '__package__': 'frappe.utils', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7f23e69cd990>, '__spec__': ModuleSpec(name='frappe.utils.bench_helper', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f23e69cd990>, origin='/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py'), '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py', '__cached__': '/home/frappe/frappe-bench/apps/frappe/frappe/utils/__pycache__/bench_helper.cpython-311.pyc', 'importlib': <module 'importlib' from '/usr/local/lib/python3.11/importlib/__init__.py'>, 'json': <module 'json' from '/usr/local/lib/python3.11/json/__init__.py'>, 'os': <module 'os' (frozen)>, 'traceback': <module 'traceback' from '/usr/local/lib/python3.11/traceback.py'>, 'warnings': <module 'warnings' from '/usr/local/lib/python3.11/warnings.py'>, 'Path': <cl...
      init_globals = None
      mod_name = '__main__'
      mod_spec = ModuleSpec(name='frappe.utils.bench_helper', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f23e69cd990>, origin='/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py')
      pkg_name = 'frappe.utils'
      script_name = None
      loader = <_frozen_importlib_external.SourceFileLoader object at 0x7f23e69cd990>
      fname = '/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py'
      cached = '/home/frappe/frappe-bench/apps/frappe/frappe/utils/__pycache__/bench_helper.cpython-311.pyc'
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
      ...skipped... 27 vars
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
      commands = {'frappe': <Group frappe>, 'get-frappe-commands': <Command get-frappe-commands>, 'get-frappe-help': <Command get-frappe-help>}
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
      self = <Group None>
      args = ()
      kwargs = {'prog_name': 'bench'}
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
      self = <Group None>
      args = ['frappe', 'migrate']
      prog_name = 'bench'
      complete_var = None
      standalone_mode = True
      windows_expand_args = True
      extra = {}
      ctx = <click.core.Context object at 0x7f23e4bff110>
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
      self = <Group None>
      ctx = <click.core.Context object at 0x7f23e4bff110>
      _process_result = <function MultiCommand.invoke.<locals>._process_result at 0x7f23e518f240>
      args = ['migrate']
      cmd_name = 'frappe'
      cmd = <Group frappe>
      sub_ctx = <click.core.Context object at 0x7f23e5151010>
      __class__ = <class 'click.core.MultiCommand'>
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
      self = <Group frappe>
      ctx = <click.core.Context object at 0x7f23e5151010>
      _process_result = <function MultiCommand.invoke.<locals>._process_result at 0x7f23e518f100>
      args = []
      cmd_name = 'migrate'
      cmd = <Command migrate>
      sub_ctx = <click.core.Context object at 0x7f23e4bfff10>
      __class__ = <class 'click.core.MultiCommand'>
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
      self = <Command migrate>
      ctx = <click.core.Context object at 0x7f23e4bfff10>
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
      _Context__self = <click.core.Context object at 0x7f23e4bfff10>
      _Context__callback = <function migrate at 0x7f23e4ba2840>
      args = ()
      kwargs = {'skip_failing': False, 'skip_search_index': False}
      ctx = <click.core.Context object at 0x7f23e4bfff10>
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
      args = ()
      kwargs = {'skip_failing': False, 'skip_search_index': False}
      f = <function migrate at 0x7f23e4ba25c0>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
      ctx = <click.core.Context object at 0x7f23e4bfff10>
      args = ()
      kwargs = {'skip_failing': False, 'skip_search_index': False}
      profile = False
      f = <function migrate at 0x7f23e4ba2520>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 599, in migrate
    ).run(site=site)
      context = {'sites': ['frontend'], 'force': False, 'verbose': False, 'profile': False}
      skip_failing = False
      skip_search_index = False
      activate_by_import = <module 'traceback_with_variables.activate_by_import' from '/home/frappe/frappe-bench/env/lib/python3.11/site-packages/traceback_with_variables/activate_by_import.py'>
      SiteMigration = <class 'frappe.migrate.SiteMigration'>
      site = 'frontend'
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 185, in run
    self.run_schema_updates()
      self = <frappe.migrate.SiteMigration object at 0x7f23e2fbedd0>
      site = 'frontend'
      filelock = <function filelock at 0x7f23e2c9f420>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 52, in wrapper
    raise e
      args = (<frappe.migrate.SiteMigration object at 0x7f23e2fbedd0>,)
      kwargs = {}
      method = <function SiteMigration.run_schema_updates at 0x7f23e2c9ef20>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 44, in wrapper
    ret = method(*args, **kwargs)
      args = (<frappe.migrate.SiteMigration object at 0x7f23e2fbedd0>,)
      kwargs = {}
      method = <function SiteMigration.run_schema_updates at 0x7f23e2c9ef20>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 119, in run_schema_updates
    frappe.model.sync.sync_all()
      self = <frappe.migrate.SiteMigration object at 0x7f23e2fbedd0>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/sync.py", line 43, in sync_all
    sync_for(app, force, reset_permissions=reset_permissions)
      force = 0
      reset_permissions = False
      app = 'india_compliance'
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/sync.py", line 111, in sync_for
    import_file_by_path(
      app_name = 'india_compliance'
      force = 0
      reset_permissions = False
      files = ['/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gst_hsn_code/gst_hsn_code.json', '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.json', '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gst_inward_supply/gst_inward_supply.json', '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry_taxes/bill_of_entry_taxes.json', '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry_item/bill_of_entry_item.json', '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_import_log/gstr_import_log.json', '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.json', '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstin/gstin.json', '/home/frappe/frappe-bench/ap...
      module_name = 'audit_trail'
      folder = '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/audit_trail'
      l = 38
      i = 6
      doc_path = '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.json'
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 148, in import_file_by_path
    import_doc(
      path = '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.json'
      force = 0
      data_import = False
      pre_process = None
      ignore_version = True
      reset_permissions = False
      docs = [{'actions': [], 'allow_rename': 1, 'autoname': 'naming_series:', 'creation': '2023-01-27 14:50:06.483818', 'default_view': 'List', 'doctype': 'DocType', 'editable_grid': 1, 'engine': 'InnoDB', 'fields': [{'fieldname': 'naming_series', 'fieldtype': 'Select', 'label': 'Naming Series', 'no_copy': 1, 'options': 'BOE-.YYYY.-', 'print_hide': 1, 'reqd': 1, 'set_only_once': 1, 'doctype': 'DocField'}, {'fieldname': 'column_break_hbfk', 'fieldtype': 'Column Break', 'doctype': 'DocField'}, {'fieldname': 'amended_from', 'fieldtype': 'Link', 'label': 'Amended From', 'no_copy': 1, 'options': 'Bill of Entry', 'print_hide': 1, 'read_only': 1, 'doctype': 'DocField'}, {'fieldname': 'column_break_2wjs', 'fieldtype': 'Column Break', 'doctype': 'DocField'}, {'fieldname': 'section_break_fqdh', 'fieldtype': 'Section Break', 'doctype': 'DocField'}, {'fieldname': 'purchase_invoice', 'fieldtype': 'Link', 'label': 'Purchase Invoice', 'options': 'Purchase Invoice', 'reqd': 1, 'doctype': 'DocField'}, {'fieldname'...
      calculated_hash = 'cedabac5ee63089938d7f608e62480a5'
      doc = {'actions': [], 'allow_rename': 1, 'autoname': 'naming_series:', 'creation': '2023-01-27 14:50:06.483818', 'default_view': 'List', 'doctype': 'DocType', 'editable_grid': 1, 'engine': 'InnoDB', 'fields': [{'fieldname': 'naming_series', 'fieldtype': 'Select', 'label': 'Naming Series', 'no_copy': 1, 'options': 'BOE-.YYYY.-', 'print_hide': 1, 'reqd': 1, 'set_only_once': 1, 'doctype': 'DocField'}, {'fieldname': 'column_break_hbfk', 'fieldtype': 'Column Break', 'doctype': 'DocField'}, {'fieldname': 'amended_from', 'fieldtype': 'Link', 'label': 'Amended From', 'no_copy': 1, 'options': 'Bill of Entry', 'print_hide': 1, 'read_only': 1, 'doctype': 'DocField'}, {'fieldname': 'column_break_2wjs', 'fieldtype': 'Column Break', 'doctype': 'DocField'}, {'fieldname': 'section_break_fqdh', 'fieldtype': 'Section Break', 'doctype': 'DocField'}, {'fieldname': 'purchase_invoice', 'fieldtype': 'Link', 'label': 'Purchase Invoice', 'options': 'Purchase Invoice', 'reqd': 1, 'doctype': 'DocField'}, {'fieldname':...
      db_modified_timestamp = datetime.datetime(2024, 3, 9, 21, 28, 26, 771013)
      is_db_timestamp_latest = True
      stored_hash = None
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 245, in import_doc
    doc.insert()
      docdict = {'actions': [], 'allow_rename': 1, 'autoname': 'naming_series:', 'creation': '2023-01-27 14:50:06.483818', 'default_view': 'List', 'doctype': 'DocType', 'editable_grid': 1, 'engine': 'InnoDB', 'fields': [{'fieldname': 'naming_series', 'fieldtype': 'Select', 'label': 'Naming Series', 'no_copy': 1, 'options': 'BOE-.YYYY.-', 'print_hide': 1, 'reqd': 1, 'set_only_once': 1, 'doctype': 'DocField'}, {'fieldname': 'column_break_hbfk', 'fieldtype': 'Column Break', 'doctype': 'DocField'}, {'fieldname': 'amended_from', 'fieldtype': 'Link', 'label': 'Amended From', 'no_copy': 1, 'options': 'Bill of Entry', 'print_hide': 1, 'read_only': 1, 'doctype': 'DocField'}, {'fieldname': 'column_break_2wjs', 'fieldtype': 'Column Break', 'doctype': 'DocField'}, {'fieldname': 'section_break_fqdh', 'fieldtype': 'Section Break', 'doctype': 'DocField'}, {'fieldname': 'purchase_invoice', 'fieldtype': 'Link', 'label': 'Purchase Invoice', 'options': 'Purchase Invoice', 'reqd': 1, 'doctype': 'DocField'}, {'fieldname':...
      data_import = False
      pre_process = None
      ignore_version = True
      reset_permissions = False
      path = '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.json'
      controller = <class 'frappe.core.doctype.doctype.doctype.DocType'>
      doc = <DocType: Bill of Entry>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 310, in insert
    self.run_post_save_methods()
      self = <DocType: Bill of Entry>
      ignore_permissions = None
      ignore_links = None
      ignore_if_duplicate = False
      ignore_mandatory = None
      set_name = None
      set_child_names = True
      d = <DocTypeLink: 94f835fc3a parent=Bill of Entry>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1118, in run_post_save_methods
    self.run_method("on_update")
      self = <DocType: Bill of Entry>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
      self = <DocType: Bill of Entry>
      method = 'on_update'
      args = ()
      kwargs = {}
      fn = <function Document.run_method.<locals>.fn at 0x7f23e1b90860>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
      self = <DocType: Bill of Entry>
      args = ()
      kwargs = {}
      hooks = [<function build_domain_restriced_doctype_cache at 0x7f23e4b21a80>, <function clear_doctype_notifications at 0x7f23e3be2480>, <function process_workflow_actions at 0x7f23e1a4c180>, <function attach_files_to_document at 0x7f23e3f2b6a0>, <function apply at 0x7f23e1a8c400>, <function update_due_date at 0x7f23e1a8c4a0>, <function apply_permissions_for_non_standard_user_type at 0x7f23e1a8dbc0>]
      method = 'on_update'
      doc_events = {'*': {'on_update': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.core.doctype.file.utils.attach_files_to_document', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply', 'frappe.automation.doctype.assignment_rule.assignment_rule.update_due_date', 'frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type'], 'after_rename': ['frappe.desk.notifications.clear_doctype_notifications'], 'on_cancel': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply'], 'on_trash': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions'], 'on_update_after_submit': ['frappe.workflow.doctype.workflow_action.workflow_action.process_w...
      handler = 'frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type'
      composed = <function Document.hook.<locals>.compose.<locals>.runner at 0x7f23e1b90cc0>
      compose = <function Document.hook.<locals>.compose at 0x7f23e1b90720>
      f = <function Document.run_method.<locals>.fn at 0x7f23e1b90860>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
      self = <DocType: Bill of Entry>
      method = 'on_update'
      args = ()
      kwargs = {}
      add_to_return_value = <function Document.hook.<locals>.add_to_return_value at 0x7f23e1b905e0>
      fn = <function Document.run_method.<locals>.fn at 0x7f23e1b90860>
      hooks = (<function build_domain_restriced_doctype_cache at 0x7f23e4b21a80>, <function clear_doctype_notifications at 0x7f23e3be2480>, <function process_workflow_actions at 0x7f23e1a4c180>, <function attach_files_to_document at 0x7f23e3f2b6a0>, <function apply at 0x7f23e1a8c400>, <function update_due_date at 0x7f23e1a8c4a0>, <function apply_permissions_for_non_standard_user_type at 0x7f23e1a8dbc0>)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
      self = <DocType: Bill of Entry>
      args = ()
      kwargs = {}
      method_object = <bound method DocType.on_update of <DocType: Bill of Entry>>
      method = 'on_update'
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 526, in on_update
    self.run_module_method("on_doctype_update")
      self = <DocType: Bill of Entry>
      allow_doctype_export = False
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 624, in run_module_method
    module = load_doctype_module(self.name, self.module)
      self = <DocType: Bill of Entry>
      method = 'on_doctype_update'
      load_doctype_module = <function load_doctype_module at 0x7f23e498ade0>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 241, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
      doctype = 'Bill of Entry'
      module = 'GST India'
      prefix = ''
      suffix = ''
      app = 'india_compliance'
      key = ('india_compliance', 'Bill of Entry', '', '')
      module_name = 'india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry'
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
      modulename = 'india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry'
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
      name = 'india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry'
      package = None
      level = 0
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
      name = 'india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry'
      package = None
      level = 0
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
      name = 'india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry'
      import_ = <function _gcd_import at 0x7f23e6b6bd80>
      module = <object object at 0x7f23e6ba0050>
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
      name = 'india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry'
      import_ = <function _gcd_import at 0x7f23e6b6bd80>
      path = ['/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry']
      parent = 'india_compliance.gst_india.doctype.bill_of_entry'
      parent_spec = ModuleSpec(name='india_compliance.gst_india.doctype.bill_of_entry', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f23e1abb750>, origin='/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/__init__.py', submodule_search_locations=['/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry'])
      parent_module = <module 'india_compliance.gst_india.doctype.bill_of_entry' from '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/__init__.py'>
      child = 'bill_of_entry'
      spec = ModuleSpec(name='india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f23e1ab96d0>, origin='/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py')
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
      spec = ModuleSpec(name='india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f23e1ab96d0>, origin='/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py')
      module = <module 'india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry' from '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py'>
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      self = <_frozen_importlib_external.SourceFileLoader object at 0x7f23e1ab96d0>
      module = <module 'india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry' from '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py'>
      code = <code object <module> at 0x559facab91a0, file "/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py", line 1>
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      f = <built-in function exec>
      args = (<code object <module> at 0x559facab91a0, file "/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py", line 1>, {'__name__': 'india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry', '__doc__': None, '__package__': 'india_compliance.gst_india.doctype.bill_of_entry', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7f23e1ab96d0>, '__spec__': ModuleSpec(name='india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f23e1ab96d0>, origin='/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py'), '__file__': '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py', '__cached__': '/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/__pycache__/bill_of_entry.cpython-311.p...
      kwds = {}
  File "/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py", line 24, in <module>
    class BillofEntry(Document):
      ...skipped... 23 vars
  File "/home/frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py", line 29, in BillofEntry
    get_voucher_subtype = AccountsController.get_voucher_subtype
      __module__ = 'india_compliance.gst_india.doctype.bill_of_entry.bill_of_entry'
      __qualname__ = 'BillofEntry'
      get_gl_dict = <function AccountsController.get_gl_dict at 0x7f23e18b9260>
      get_value_in_transaction_currency = <function AccountsController.get_value_in_transaction_currency at 0x7f23e18b9300>
builtins.AttributeError: type object 'AccountsController' has no attribute 'get_voucher_subtype'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
This issue can occur only because of 2 reasons:
- Incorrect App version. ERPNext v14 with India Compliance v15. This is very less likely.
- Some issues with your installation or docker build.

This is not a bug or issue with India Compiance App as test cases are passing. To ensure test cases pass, we first have to install the India Compliance App and then run test cases.
https://github.com/resilient-tech/india-compliance/actions/runs/8184002382/job/22377727782

If you need more help with Installation, discuss forum would be the right place.

**Comment by rajamuppidi** [comment]
I am on ERP version 15 and trying to install India-compliance V15 branch
