### ISSUE TITLE
Installation error ERPNext 15: Please help Guide

### ISSUE THREAD

**Issue by rajamuppidi** [resilient-tech/india-compliance#1872]
### Information about bug

On a fresh ERPNext 15 unable to install your india-compliance app

bench get-app --branch version-15 https://github.com/resilient-tech/india-compliance.git

frappe@cba17187b621:~/frappe-bench$ bench --site mysite.com install-app india_compliance 
App erpnext already installed

Installing india_compliance...
Installation for India Compliance failed due to an error. Please try re-installing the app or report the issue on https://github.com/resilient-tech/india-compliance/issues/new if not resolved.
An error occurred while installing india_compliance: Could not find DocType: Bill of Entry
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 311, in install_app
    frappe.get_attr(after_install)()
  File "apps/india_compliance/india_compliance/install.py", line 73, in after_install
    raise e
  File "apps/india_compliance/india_compliance/install.py", line 52, in after_install
    setup_audit_trail()
  File "apps/india_compliance/india_compliance/audit_trail/setup.py", line 15, in setup_fixtures
    create_property_setters_for_versioning()
  File "apps/india_compliance/india_compliance/audit_trail/setup.py", line 35, in create_property_setters_for_versioning
    property_setter.insert()
  File "apps/frappe/frappe/model/document.py", line 278, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 918, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 575, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 526, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find DocType: Bill of Entry

### Version

ERPNext v15

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Duplicate: https://discuss.frappe.io/t/how-to-install-india-compliance-running-on-docker-instance/112996/7

Invalid: It looks like an invalid installation configuration. Passing test cases ensures that installation should be flawless. Try it with frappe-cloud if the issue persists.

**Comment by rajamuppidi** [comment]
ERPNext: v15.17.1

Frappe Framework: v15.17.3

Helpdesk: v0.10.0 (main)

Frappe HR: v16.0.0-dev (develop)


Can you please provide a command to install the India-compliance app for ERPNext 15? I have been trying for the last one month nothing has been working
