### ISSUE TITLE
Uninstall Error

### ISSUE THREAD

**Issue by sumeetagra** [resilient-tech/india-compliance#2239]
### Information about bug

erpnext@vps-3ab1fb68:~/frappe-bench$ bench remove-app india_compliance
Checking if app installed on active sites...
$ /home/erpnext/frappe-bench/env/bin/python -m pip uninstall -y india_compliance
Found existing installation: india_compliance 15.8.1
Uninstalling india_compliance-15.8.1:
  Successfully uninstalled india_compliance-15.8.1
ERROR: [Errno 2] No such file or directory: 'apps/india-compliance'
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'apps/india-compliance' -> 'archived/apps/india-compliance-2024-06-12'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/make.py", line 197, in remove_app
    bench.uninstall(app_name, no_backup=no_backup, force=force)
  File "/usr/local/lib/python3.10/dist-packages/bench/bench.py", line 130, in uninstall
    self.apps.remove(App(app, bench=self, to_clone=False), no_backup=no_backup)
  File "/usr/local/lib/python3.10/dist-packages/bench/bench.py", line 317, in remove
    app.remove(no_backup=no_backup)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 216, in remove
    shutil.move(active_app_path, archived_app_path)
  File "/usr/lib/python3.10/shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'apps/india-compliance'

### Version

ERPNext: v15.27.4 (version-15)

Frappe Framework: v15.29.2 (version-15)

Frappeauth App: v0.0.1 (master)

Goyal App: v0.0.1 (main)

Frappe HR: v15.22.1 (version-15)

India Compliance: v15.8.1 (version-15)

Payments: v0.0.1 (develop)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
This error has nothing to do with the India Compliance App.
You should create an Issue in [Frappe Repo](https://github.com/frappe/frappe)
