### ISSUE TITLE
Not able to download latest GSTR 2A / 2B

### ISSUE THREAD

**Issue by lato-tech** [resilient-tech/india-compliance#2251]
### Information about bug

Hi,
I was trying to download the entries of GSTR 2A / 2B for the current month and I am getting the following error:

"API Request Failed
Invalid Data Format"

Please let us know what the issue is. Need to file our returns on or before 20th of May 2024.
![Screenshot 2024-06-15 140115](https://github.com/resilient-tech/india-compliance/assets/129725214/98d0ca74-ce06-4bd5-aa1b-2f622542478c)

### Version

ERPNext: v15.27.1 (version-15)

Frappe Framework: v15.29.1 (version-15)

India Compliance: v15.7.5 (version-15)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laxmantandon** [comment]
Hi,

We are also facing same issue while downloading the gstr 2b data.

**Installed Apps:**
ERPNext: v14.50.0
Frappe Framework: v14.56.1
Frappe HR: v14.18.0
India Compliance: v14.19.4

**Error Screenshot**
![image](https://github.com/resilient-tech/india-compliance/assets/24727535/17c908c7-0788-49d6-bed2-097d906105d9)


**below is the traceback**
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 323, in run_doc_method
    response = doc.run_method(method, **args)
  File "apps/frappe/frappe/model/document.py", line 919, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1281, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1263, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 916, in fn
    return method_object(*args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py", line 98, in download_gstr_2b
    return download_gstr_2b(self.company_gstin, periods, otp)
  File "apps/india_compliance/india_compliance/gst_india/utils/gstr/__init__.py", line 156, in download_gstr_2b
    response = api.get_data(return_period, otp)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 368, in get_data
    return self.get(
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 270, in get
    return self._request("get", action, return_period, params, endpoint, None, otp)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 248, in _request
    response = self.autheticate_with_otp(otp=otp)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 101, in autheticate_with_otp
    return self.request_otp()
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 73, in request_otp
    response = super().post(
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 81, in post
    return self._make_request("POST", *args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 161, in _make_request
    raise e
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 156, in _make_request
    response_json = self.process_response(response_json)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 279, in process_response
    self.handle_error_response(response)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/returns.py", line 308, in handle_error_response
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 534, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 502, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 451, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Invalid Data Format
request.js:457:14

**Comment by vorasmit** [comment]
This has been fixed here:

https://github.com/resilient-tech/india-compliance/pull/2209

Update the app and try again.

**Comment by lato-tech** [comment]
Hi,
I have updated the the India Compliance, Frappe and ERP Next apps. Still I am getting the same error.

Have I missed out on something?

**Comment by laxmantandon** [comment]
> This has been fixed here:
> 
> #2209
> 
> Update the app and try again.

Is it merged in branch version-14 ?

**Comment by sagarvora** [comment]
released in v14.27.0

**Comment by sagarvora** [comment]
> Is it merged in branch version-14 ?

yes

**Comment by sagarvora** [comment]
> Have I missed out on something?

Which versions are you on now?

**Comment by laxmantandon** [comment]
> > Have I missed out on something?
> 
> Which versions are you on now?

version-14, just saw your message that you have already released it in version-14 branch, i will pull the updates..

Thanks for your quick response.

**Comment by lato-tech** [comment]
> > Have I missed out on something?
> 
> Which versions are you on now?

ERPNext: v15.27.1 (version-15)

Frappe Framework: v15.29.1 (version-15)

India Compliance: v15.7.5 (version-15)

Same as before. It is showing me : ~/frappe-bench/apps/india_compliance$ git pull
**Already up to date.**

**Comment by lato-tech** [comment]
Hi,
Any updates?

**Comment by vorasmit** [comment]
Fix was released in [v15.8.0](https://github.com/resilient-tech/india-compliance/releases/tag/v15.8.0)

Latest release is v15.8.1. Your version is v15.7.5.

You might be using customized version of IC and hence probably you don't see an update.

**Comment by lato-tech** [comment]
Have updated to the latest version i.e.: India Compliance: v15.8.1 (version-15). I am getting this error now. 

"Failed to get method for command india_compliance.gst_india.utils.gstr.gstr.validate_company_gstins with No module named 'india_compliance.gst_india.utils.gstr.gstr'"
![Screenshot 2024-06-16 193534](https://github.com/resilient-tech/india-compliance/assets/129725214/d982911a-38ef-4f8b-8643-0170d18c5179)

Please let me know the solution ASAP as we are close to the deadline.

Thanks.

**Comment by vorasmit** [comment]
@nmchm 

You should seriously consider using frappe cloud. The issues you are facing are more related to your deployment then the India Compliance App.

Looks like JS build issue / python cache issue.

**Comment by lato-tech** [comment]
Got it. Resolved.

Thanks a lot for the help!
