### ISSUE TITLE
Negative Other Charges Amount API Request Failed

### ISSUE THREAD

**Issue by creative-paramu** [resilient-tech/india-compliance#2310]
### Information about bug

I was Creating invoice with Sales Taxes and Charges Template, i was adding freight forward charges in negative(expense amount for current invoice) and submit the invoice
![image](https://github.com/resilient-tech/india-compliance/assets/101092028/f7f65ce6-c9de-4467-b7c7-44ba44120ee2)
After that i create E invoice for the Sales invoice its show the API Request Failed Error
I attach the Error Message Image, 
How to Solve this Error?
![image](https://github.com/resilient-tech/india-compliance/assets/101092028/75188b10-16f5-4129-a40c-2c42b647f099)

### Version

ERPNext: v15.24.1 (version-15)
Frappe Framework: v15.27.0 (version-15)
India Compliance: v15.7.4 (version-15)

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/utils/e_invoice.py", line 175, in generate_e_invoice
    raise e
  File "apps/india_compliance/india_compliance/gst_india/utils/e_invoice.py", line 128, in generate_e_invoice
    result = api.generate_irn(data)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/e_invoice.py", line 77, in generate_irn
    result = self.post(endpoint="invoice", json=data)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 81, in post
    return self._make_request("POST", *args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 161, in _make_request
    raise e
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 156, in _make_request
    response_json = self.process_response(response_json)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 182, in process_response
    self.handle_error_response(response)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 197, in handle_error_response
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 645, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: 5002 : The field Other Charges must match the regular expression '^\d+.?\d{0,2}$'., 5002 : The field Other Charges must be between 0 and 99999999999999.98.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Why is the freight -ve for this invoice? Such cases are not supported for e-Invoice by govt.

Suggestion:
- Add -ve freight as first row.
- Apply taxes `on previous row` after freight is reduced.

This will internally reduce taxable value for items (proportionately) and will be reported for e-invoice

**Comment by creative-paramu** [comment]
Actual invoice(scenario) of this invoice is to less the expense amount from this invoice. When the client file this invoice, GST Portal display the 50rs amount in discount column, reference screenshot is shared below.

This is our scenario we are looking for, If there is any alternate way to achieve this, let us know please.
![WhatsApp Image 2024-06-26 at 5 31 41 PM(2)](https://github.com/resilient-tech/india-compliance/assets/101092028/1b0bef93-bd74-4f76-b0b1-b59bf2018b8c)

![WhatsApp Image 2024-06-26 at 5 40 27 PM](https://github.com/resilient-tech/india-compliance/assets/101092028/52f7b123-62e5-432e-9228-8f01d7505237)

**Comment by vorasmit** [comment]
This is doable. Thanks for the suggestion.

**Comment by creative-paramu** [comment]
Thank you for considering it, 
We got urgent requirement from client, so we found it, 
Hope we are expecting this feature in the next release
