### ISSUE TITLE
Update instructions for docker setup in Readme

### ISSUE THREAD

**Issue by suryawomshi** [resilient-tech/india-compliance#2355]
### Information about bug

How to produce error:

**ERPNext Installation**
On  Ubuntu 22.04.4 LTS  Install frappe bench using [Easy Install Script](https://github.com/frappe/bench/tree/develop#easy-install-script) 

wget https://raw.githubusercontent.com/frappe/bench/develop/easy-install.py
python3 easy-install.py -p -n erp -s erp.mydomain.com --email email@mydomain.com

Installation succeeds without any error and  ERP next working on erp.mydomain.com

**India Compliance Installation**
Login to Docker Backed  Container Interactively 

docker exec -it erp-backend-1 bash
bench get-app --branch version-15 --resolve-deps  https://github.com/resilient-tech/india-compliance.git
(till this step site is working)
bench --site erp.mydomain.com install-app india_compliance 

installation succeeds without error but front end gives **Internal Server Error**
![Screenshot 2024-07-05 163605](https://github.com/resilient-tech/india-compliance/assets/47660298/40d0fd36-1043-4e37-afca-f7614f8a798a)
![Screenshot 2024-07-05 163733](https://github.com/resilient-tech/india-compliance/assets/47660298/369e1c33-e8ef-4914-962f-f8cded8a9b1f)

### Version

erpnext 15.29.2
frappe 15.33.2
india_compliance 15.9.2

### Relevant log output / Stack trace / Full Error Message.

```shell
[frappe.log](https://github.com/user-attachments/files/16108971/frappe.log)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suryawomshi** [comment]
Frappe Log file: 
 
2024-07-05 11:06:10,984 ERROR frappe Could not take error snapshot: 'NoneType' object has no attribute 'get'
Site: erp.bharathisystems.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 172, in init_request
    frappe.init(site=site, sites_path=_sites_path, force=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 313, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1692, in setup_module_map
    for module in get_module_list(app):
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1540, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1505, in get_app_path
    return get_pymodule_path(app_name, *joins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1535, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1476, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'india_compliance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
                ^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1333, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 70, in get_controller
    site_controllers[doctype] = import_controller(doctype)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 95, in import_controller
    module = load_doctype_module(doctype, module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 244, in load_doctype_module
    app = get_module_app(module)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 267, in get_module_app
    app = frappe.local.module_app.get(scrub(module))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by vorasmit** [comment]
Can you try running following in bench directory?
`bench setup requirements`

Looks like issue with your installation.

**Comment by suryawomshi** [comment]
on running bench setup requirements  i am getting below error. I have installed as per official documentation. 

I may be wrong here but Docker suppose to make deployments easy on different environments. 


frappe@fe8a0a73f2c5:~/frappe-bench$ bench setup requirements
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade pip
Installing 2 applications...
ERROR: /home/frappe/frappe-bench/apps/frappe
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/commands/setup.py", line 230, in setup_requirements
    bench.setup.requirements(apps=apps)
  File "/usr/local/lib/python3.11/site-packages/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/bench.py", line 464, in requirements
    app = App(path_to_app, bench=self.bench, to_clone=False).install(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 185, in __init__
    super().__init__(name, branch, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 85, in __init__
    self.setup_details()
  File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 101, in setup_details
    self._setup_details_from_mounted_disk()
  File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 119, in _setup_details_from_mounted_disk
    self.git_repo = git.Repo(self.mount_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/repo/base.py", line 289, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/frappe/frappe-bench/apps/frappe

**Comment by suryawomshi** [comment]
How to install official or custom apps?
In case of production setup you need to build your custom image for installing apps. This repository only publishes frappe/erpnext image with no additional app. **You CANNOT bench get-app in running containers.**

This means I cannot bench get-app in production containers? can someone confirm.

**Comment by vorasmit** [comment]
Installation method specified in readme is for manual installation method.

Following guide should be useful for docker setup:
https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md#load-custom-apps-through-json

We'll update readme to accommodate docker installation.
