### ISSUE TITLE
Tax amount should be positive for GST Account INPUT IGST

### ISSUE THREAD

**Issue by sumeetagra** [resilient-tech/india-compliance#2437]
### Information about bug

While issuing Debit Note using In Return Option under Purchase Invoice, Error for Positive Value in GST account is raised, whereas Debit Note will have a Negative Tax Value.

### Version

ERPNext: v15.29.3 (version-15)

Frappe Framework: v15.34.1 (version-15)

Frappeauth App: v0.0.1 (master)

Goyal App: v0.0.1 (main)

Frappe HR: v15.23.1 (version-15)

India Compliance: v15.10.2 (version-15)

Payments: v0.0.1 (version-15)

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 373, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/purchase_invoice.py", line 43, in validate
    if validate_transaction(doc) is False:
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 1566, in validate_transaction
    validate_reverse_charge_transaction(doc)
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 1079, in validate_reverse_charge_transaction
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 645, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Row #1: Tax amount should be positive for GST Account INPUT IGST - GIPL
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Fixed in #2420 
Will be released today.
