### ISSUE TITLE
just installed app and giving a problem, please find the error below

### ISSUE THREAD

**Issue by ganureddy** [resilient-tech/india-compliance#2507]
### App Versions

```
{
	"erpnext": "15.32.1",
	"frappe": "15.37.0",
	"hrms": "15.25.2",
	"india_compliance": "15.12.1",
	"payments": "0.0.1"
}
```

### Route

```
Workspaces/GST India
```

### Traceback

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/doctype/number_card/number_card.py", line 154, in get_result
    res = frappe.get_list(
          ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 2032, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
             ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
           ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 234, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'tabSales Invoice.einvoice_status' in 'where clause'")
```

### Request Data

```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"Pending e-Invoices\",\"owner\":\"Administrator\",\"creation\":\"2023-07-25 15:10:39.976867\",\"modified\":\"2024-04-09 11:45:32.550901\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"is_standard\":1,\"module\":\"GST India\",\"label\":\"Pending e-Invoices\",\"type\":\"Document Type\",\"method\":\"\",\"function\":\"Count\",\"aggregate_function_based_on\":\"\",\"document_type\":\"Sales Invoice\",\"parent_document_type\":\"\",\"report_function\":\"Sum\",\"is_public\":1,\"filters_config\":\"\",\"show_percentage_stats\":0,\"stats_time_interval\":\"Daily\",\"filters_json\":\"[[\\\"Sales Invoice\\\",\\\"einvoice_status\\\",\\\"=\\\",\\\"Pending\\\",false],[\\\"Sales Invoice\\\",\\\"docstatus\\\",\\\"=\\\",\\\"1\\\",false]]\",\"dynamic_filters_json\":\"[]\",\"color\":\"#EC864B\",\"doctype\":\"Number Card\",\"__last_sync_on\":\"2024-08-08T10:55:40.664Z\"}",
		"filters": "[[\"Sales Invoice\",\"einvoice_status\",\"=\",\"Pending\",false],[\"Sales Invoice\",\"docstatus\",\"=\",\"1\",false]]"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.doctype.number_card.number_card.get_result",
	"request_id": null
}
```

### Response Data

```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'tabSales Invoice.einvoice_status' in 'where clause'\")",
	"exc_type": "OperationalError"
}
```

### Version

frappe version -15
erpnext - 15
india Compliance - 15

### Relevant log output / Stack trace / Full Error Message.

*No response*

### Code of Conduct

* [ ] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
This is because app may not have been installed properly/completely. Was there any error when you tried to install the app? Are you on Frappe Cloud or Self Hosted?

**Comment by vorasmit** [comment]
You may please add more context here to help you further, if the issue still persists.
