### ISSUE TITLE
Error when transferring to new bench

### ISSUE THREAD

**Issue by nakul80** [resilient-tech/india-compliance#2616]
### Information about bug

Hosted on Frappecloud so cannot manually initiate create_custom_fields() as is mentioned in solutions to other similar issues. I tried to install new site and same error.

### Version

```
"erpnext": "15.35.1",
"frappe": "15.40.6",
"india_compliance": "15.0.0-dev"
```

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.35.1",
	"frappe": "15.40.6",
	"india_compliance": "15.0.0-dev"
}
```

### Route

```
Form/Sales Invoice/SI-25-0668
```

### Traceback

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
           ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
           ^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 373, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1094, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/overrides/sales_invoice.py", line 52, in validate
    if validate_transaction(doc) is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 931, in validate_transaction
    if ignore_gst_validations(doc):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 989, in ignore_gst_validations
    or validate_items(doc) is False
       ^^^^^^^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 377, in validate_items
    if row.is_non_gst:
       ^^^^^^^^^^^^^^
AttributeError: 'SalesInvoiceItem' object has no attribute 'is_non_gst'
```

### Response Data

```
{
	"exception": "AttributeError: 'SalesInvoiceItem' object has no attribute 'is_non_gst'",
	"exc_type": "AttributeError",
	"_exc_source": "india_compliance (app)"
}
```

```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmU1NWY0MDQ5YzY4N2Y5NWNhNDMwNjYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.OlEo1nbTdjl3WnUA6NXNS4nMfzVbUL4j44q7JT_IKvw">Huly&reg;: <b>IC-2737</b></a></sub>

**Comment by vorasmit** [comment]
Looks like you are on incorrect branch of India Compliance App. Please change the branch to version-15.
