### ISSUE TITLE
GSTR 1 Log Error

### ISSUE THREAD

**Issue by bhavyajicomputers** [resilient-tech/india-compliance#2637]
### App Versions

```
{
	"erpnext": "14.73.0",
	"frappe": "14.80.1",
	"hrms": "14.30.1",
	"india_compliance": "14.30.4",
	"komori": "0.0.1",
	"payments": "0.0.1"
}
```

### Route

```
Workspaces/Home
```

### Traceback

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 97, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/load.py", line 72, in getdoctype
    docs = get_meta_bundle(doctype)
  File "apps/frappe/frappe/desk/form/load.py", line 83, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "apps/frappe/frappe/desk/form/meta.py", line 41, in get_meta
    meta = FormMeta(doctype)
  File "apps/frappe/frappe/desk/form/meta.py", line 55, in __init__
    self.load_assets()
  File "apps/frappe/frappe/desk/form/meta.py", line 65, in load_assets
    self.add_code()
  File "apps/frappe/frappe/desk/form/meta.py", line 120, in add_code
    self.add_html_templates(path)
  File "apps/frappe/frappe/desk/form/meta.py", line 135, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'apps/india_compliance/india_compliance/gst_india/doctype/gstr_1_log'
```

### Request Data

```
{
	"type": "GET",
	"args": {
		"doctype": "GSTR-1 Log",
		"with_parent": 1,
		"cached_timestamp": null
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoctype"
}
```

### Response Data

```
{
	"exception": "FileNotFoundError: [Errno 2] No such file or directory: 'apps/india_compliance/india_compliance/gst_india/doctype/gstr_1_log'"
}
```

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmYyZjdjOWMyNDM5YjlmMjQ1OTU1ZTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.dlMOL4D9v4NPzZmhlN4W0Yx1aIo6Ea7-WvyDKdMv3_k">Huly&reg;: <b>IC-2760</b></a></sub>

**Comment by ljain112** [comment]
Hello,

GSTR-1 Log is replaced with GST Return Log.
Looks like JS build issue / python cache issue.

Kindly clear-cache and execute bench build
