### ISSUE TITLE
Update issue  - india_compliance/patches/v15/migrate_boe_taxes_to_ic_taxes.py"

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#2833]
### Information about bug

We have no Workflow created in ERP.

https://github.com/frappe/frappe/issues/28723

### Version

v15 latest

### Relevant log output / Stack trace / Full Error Message.

```shell
Executing india_compliance.patches.v15.migrate_boe_taxes_to_ic_taxes in blissteringepl.com (_289b398fca2e679f)
Queued rebuilding of search index for blissteringepl.com

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/blisstering/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/blisstering/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/blisstering/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/blisstering/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/blisstering/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/blisstering/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/blisstering/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/commands/site.py", line 686, in migrate
    SiteMigration(
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/migrate.py", line 186, in run
    self.run_schema_updates()
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/migrate.py", line 52, in wrapper
    raise e
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/migrate.py", line 44, in wrapper
    ret = method(*args, **kwargs)
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/migrate.py", line 121, in run_schema_updates
    frappe.modules.patch_handler.run_all(
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 76, in run_all
    run_patch(patch)
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 62, in run_patch
    if not run_single(patchmodule=patch):
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 152, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 188, in execute_patch
    _patch()
  File "/home/blisstering/frappe-bench/apps/india_compliance/india_compliance/patches/v15/migrate_boe_taxes_to_ic_taxes.py", line 20, in execute
    ic_taxes_doc.insert(ignore_if_duplicate=True)
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/model/document.py", line 286, in insert
    self.check_if_latest()
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/model/document.py", line 823, in check_if_latest
    self.check_docstatus_transition(0)
  File "/home/blisstering/frappe-bench/apps/frappe/frappe/model/document.py", line 857, in check_docstatus_transition
    raise frappe.DocstatusTransitionError(
frappe.exceptions.DocstatusTransitionError: Cannot change docstatus from 0 (Draft) to 2 (Cancelled)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU3MzUxMTFlMDYzMmRkMDhlMjhjZGMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.GZS2-PQWU6BzFlb4QtJ_thgjCfuOiFZsVAas2LTm6RA">Huly&reg;: <b>IC-2959</b></a></sub>

**Comment by dineshpanchal93** [comment]
Anyone is facing same issue ?

**Comment by ljain112** [comment]
https://github.com/resilient-tech/india-compliance/pull/2826
