### ISSUE TITLE
vjnlfdjvhnfds

### ISSUE THREAD

**Issue by Abdeali099** [resilient-tech/india-compliance#2838]
### Information about bug

I am Abdeali

### Version

h

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):File "apps/frappe/frappe/app.py", line 118, in applicationresponse = frappe.api.handle(request)^^^^^^^^^^^^^^^^^^^^^^^^^^File "apps/frappe/frappe/api/__init__.py", line 49, in handledata = endpoint(**arguments)^^^^^^^^^^^^^^^^^^^^^File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_callreturn frappe.handler.handle()^^^^^^^^^^^^^^^^^^^^^^^File "apps/frappe/frappe/handler.py", line 49, in handledata = execute_cmd(cmd)^^^^^^^^^^^^^^^^File "apps/frappe/frappe/handler.py", line 85, in execute_cmdreturn frappe.call(method, **frappe.form_dict)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "apps/frappe/frappe/__init__.py", line 1807, in callreturn fn(*args, **newargs)^^^^^^^^^^^^^^^^^^^^File "apps/frappe/frappe/handler.py", line 295, in run_doc_methodresponse = doc.run_method(method, **args)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "apps/frappe/frappe/model/document.py", line 1061, in run_methodout = Document.hook(fn)(self, *args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "apps/frappe/frappe/model/document.py", line 1448, in composerreturn composed(self, method, *args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "apps/frappe/frappe/model/document.py", line 1426, in runneradd_to_return_value(self, fn(self, *args, **kwargs))^^^^^^^^^^^^^^^^^^^^^^^^^File "apps/frappe/frappe/model/document.py", line 1058, in fnreturn method_object(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapperreturn func(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^TypeError: PaymentEntry.allocate_amount_to_references() missing 1 required positional argument: 'paid_amount'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abdeali099** [comment]
### IGNORE, IT WAS JUST FOR TESTING
