### ISSUE TITLE
Error on deleting draft sales invoice

### ISSUE THREAD

**Issue by rtdany10** [resilient-tech/india-compliance#424]
![image](https://user-images.githubusercontent.com/52111700/209811170-274c2518-129d-4f01-9701-0a952fd62b78.png)

Traceback:
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1590, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/client.py", line 273, in delete
    delete_doc(doctype, name)
  File "apps/frappe/frappe/client.py", line 480, in delete_doc
    frappe.delete_doc(doctype, name, ignore_missing=False)
  File "apps/frappe/frappe/__init__.py", line 1238, in delete_doc
    return frappe.model.delete_doc.delete_doc(
  File "apps/frappe/frappe/model/delete_doc.py", line 109, in delete_doc
    doc.run_method("on_trash")
  File "apps/frappe/frappe/model/document.py", line 908, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1258, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1242, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 731, in ignore_logs_on_trash
    if "e-Waybill Log" not in delete_doc.doctypes_to_skip:
AttributeError: module 'frappe.model.delete_doc' has no attribute 'doctypes_to_skip'
```

**Comment by rtdany10** [comment]
Frappe Framework: v14.21.0 (HEAD)
ERPNext: v14.11.1 (HEAD)
India Compliance: v14.0.8 (HEAD)

**Comment by sagarvora** [comment]
Thanks for reporting. It is my team who had deleted this constant from Frappe in https://github.com/frappe/frappe/pull/19347. Will fix 👍🏼
