### ISSUE TITLE
Billing Address GSTIN and Company GSTIN cannot be the same

### ISSUE THREAD

**Issue by sjain17** [resilient-tech/india-compliance#529]
### Information about bug

In case of stock transfer invoice the company GSTIN and Billing Address GSTIN may be same. This should not be a validation for internal customer sales invoices. 

For example - I have one branch in Mumbai and another branch in Pune. I may generated a sales invoice and GSTIN for Pune and Mumbai will be same because both are under Maharashtra State, hence system should allow these type of sales invoices.

### Version

ERPNext: v14.11.1 (version-14)
Frappe Framework: v14.21.0 (version-14)
Frappe HR: v1.0.0 (develop)
India Compliance: v14.0.8 (version-14)
Payments: v0.0.1 (develop)

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1590, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 304, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 326, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 258, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1039, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 908, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1258, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1242, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/sales_invoice.py", line 53, in validate
    validate_billing_address_gstin(doc)
  File "apps/india_compliance/india_compliance/gst_india/overrides/sales_invoice.py", line 96, in validate_billing_address_gstin
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Billing Address GSTIN and Company GSTIN cannot be the same
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
Please use **Delivery Note** for cases where GSTIN is the same.

**Comment by sjain17** [comment]
An invoice is mandatory for within-state transfers as well. How can someone send valuables items without Sales Invoice?

**Comment by vorasmit** [comment]
Can you please confirm this with your CA?
If applicable, kindly share appropriate article or reference.

**Comment by sagarvora** [comment]
@sjain17 Kindly note that our recommendation to use Delivery Note is in accordance with govt's allowed document types for supply from "Self" to "Self" when generating an e-Waybill:
https://docs.ewaybillgst.gov.in/apidocs/sub-docType-mapping.html

Is there any other reason why you need to record this in sales invoice?

**Comment by vorasmit** [comment]
#632 
FYI
