### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable on installing IC

### ISSUE THREAD

**Issue by DaizyModi** [resilient-tech/india-compliance#566]
### Information about bug

`TypeError: 'NoneType' object is not subscriptable` while Installing India Compliance.

**Steps to Reproduce Error**

If you have already installed ERPNext app,
1. Remove current fiscal **i.e 2023-2024** if you have already added in `Fiscal Year`.
2. Clone the India Compliance app. If you have it, just go to step - 3.
3. Install it in your site.

**Error**

![IC fiscal year details error](https://user-images.githubusercontent.com/54097382/230324989-5e51527f-ef99-4850-995e-fb75f79560aa.png)

### Version

India Compliance Version - Develop

### Relevant log output / Stack trace / Full Error Message.

```shell
App erpnext already installed

Installing india_compliance...
Updating DocTypes for india_compliance: [====================] 100%
Setting up Income Tax...
Setting up GST...
Patching Existing Data...
Installation for India Compliance failed due to an error. Please try re-installing the app or report the issue on https://github.com/resilient-tech/india-compliance/issues/new if not resolved.
An error occurred while installing india_compliance: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 463, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 303, in install_app
    frappe.get_attr(after_install)()
  File "apps/india_compliance/india_compliance/install.py", line 62, in after_install
    raise e
  File "apps/india_compliance/india_compliance/install.py", line 51, in after_install
    run_post_install_patches()
  File "apps/india_compliance/india_compliance/install.py", line 75, in run_post_install_patches
    frappe.get_attr(f"india_compliance.patches.post_install.{patch}.execute")()
  File "apps/india_compliance/india_compliance/patches/post_install/create_company_fixtures.py", line 22, in execute
    create_income_tax_fixtures(company)
  File "apps/india_compliance/india_compliance/income_tax_india/overrides/company.py", line 20, in create_company_fixtures
    set_tax_withholding_category(company)
  File "apps/india_compliance/india_compliance/income_tax_india/overrides/company.py", line 43, in set_tax_withholding_category
    docs = get_tds_details(accounts, fiscal_year_details)
  File "apps/india_compliance/india_compliance/income_tax_india/overrides/company.py", line 96, in get_tds_details
    "from_date": fiscal_year_details[1],
TypeError: 'NoneType' object is not subscriptable
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
@vorasmit Thoughts? This is what ERPNext intended with the `try...except` block: https://github.com/frappe/erpnext/pull/24130
