### ISSUE TITLE
While Making Delivery Note from Pick List

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#567]
### Information about bug

While Making Delivery Note from Pick List

### Version

ERPNext: v14.20.2 (version-14)

Frappe Framework: v14.31.0 (version-14)

Frappe Whatsapp: v0.0.2 (master)

Gatepass: v0.0.1 (main)

Frappe HR: v14.2.1 (version-14)

India Compliance: v14.5.1 (version-14)

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/model/mapper.py", line 36, in make_mapped_doc
    return method(source_name)
  File "apps/erpnext/erpnext/stock/doctype/pick_list/pick_list.py", line 728, in create_delivery_note
    delivery_note = create_dn_wo_so(pick_list)
  File "apps/erpnext/erpnext/stock/doctype/pick_list/pick_list.py", line 746, in create_dn_wo_so
    delivery_note.insert(ignore_mandatory=True)
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1248, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 721, in validate_transaction
    validate_mandatory_fields(doc, ("company_gstin", "place_of_supply"))
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 112, in validate_mandatory_fields
    frappe.throw(error_message, title=_("Missing Required Field"))
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: <strong>Company GSTIN</strong> is a mandatory field for GST Transactions
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dineshpanchal93** [comment]
@sagarvora can you please check on prioirity
