### ISSUE TITLE
'None' has no attribute 'signed_qr_code'

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#569]
### Information about bug

E-invoice Generated and Eway bill also generated 
But QR code and Eway bill pdf not attached

### Version

ERPNext: v14.20.2 (version-14)

Frappe Framework: v14.31.0 (version-14)

Frappe Whatsapp: v0.0.2 (master)

Frappe HR: v14.2.1 (version-14)

India Compliance: v14.5.1 (version-14)

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"addon_s_bom": "0.0.1",
	"addon_s_hr": "0.0.1",
	"addon_s_stocks": "0.0.1",
	"chat": "0.0.1",
	"erpnext": "14.20.2",
	"frappe": "14.31.0",
	"frappe_whatsapp": "0.0.2",
	"gatepass": "0.0.1",
	"hrms": "14.2.1",
	"india_compliance": "14.5.1",
	"sync_emp_checkin": "0.0.1"
}
```
### Route
```
print/Sales Invoice/SINV/23-24/019
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/www/printview.py", line 295, in get_html_and_style
    html = get_rendered_template(
  File "apps/frappe/frappe/www/printview.py", line 208, in get_rendered_template
    html = template.render(args, filters={"len": len})
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 243, in top-level template code
  File "env/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/utils/jinja.py", line 92, in get_qr_code
    return pyqrcode.create(qr_text).png_as_base64_str(scale=scale, quiet_zone=1)
  File "env/lib/python3.10/site-packages/pyqrcode/__init__.py", line 111, in create
    return QRCode(content, error, version, mode, encoding)
  File "env/lib/python3.10/site-packages/pyqrcode/__init__.py", line 137, in __init__
    guessed_content_type, encoding = self._detect_content_type(content, encoding)
  File "env/lib/python3.10/site-packages/pyqrcode/__init__.py", line 307, in _detect_content_type
    c = content.encode('shiftjis')
jinja2.exceptions.UndefinedError: 'None' has no attribute 'signed_qr_code'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"SINV/23-24/019\",\"owner\":\"chetan.g@blissteringepl.com\",\"creation\":\"2023-04-07 15:00:35.585320\",\"modified\":\"2023-04-07 15:01:39.728005\",\"modified_by\":\"chetan.g@blissteringepl.com\",\"docstatus\":1,\"idx\":0,\"title\":\"PRECIOUS ELECTRO TRADE PVT LTD\",\"naming_series\":\"SINV/23-24/.###\",\"customer\":\"CUST-2022-00011\",\"irn\":\"7be594a8a59ce2b32be61c073924171899fdef175ed1962229a801219c497f45\",\"customer_name\":\"PRECIOUS ELECTRO TRADE PVT LTD\",\"ewaybill\":\"491327558486\",\"tax_id\":\"19AAECP3318H1ZF\",\"company\":\"Blisstering Electronics Private Limited\",\"company_tax_id\":\"09AAGCB7154D1ZQ\",\"posting_date\":\"2023-04-07\",\"posting_time\":\"15:01:36.580821\",\"set_posting_time\":0,\"due_date\":\"2023-04-22\",\"is_pos\":0,\"is_consolidated\":0,\"is_return\":0,\"reason_for_issuing_document\":\"\",\"update_billed_amount_in_sales_order\":0,\"is_debit_note\":0,\"is_reverse_charge\":0,\"is_export_with_gst\":0,\"currency\":\"INR\",\"conversion_rate\":1,\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"update_stock\":0,\"set_warehouse\":\"Finished Goods - BEPL\",\"total_qty\":3000,\"total_net_weight\":0,\"base_total\":555000,\"base_net_total\":555000,\"total\":555000,\"net_total\":555000,\"tax_category\":\"Out-State\",\"taxes_and_charges\":\"Output GST Out-state - BEPL\",\"base_total_taxes_and_charges\":99900,\"total_taxes_and_charges\":99900,\"base_grand_total\":654900,\"base_rounding_adjustment\":0,\"base_rounded_total\":654900,\"base_in_words\":\"INR Six Lakh, Fifty Four Thousand, Nine Hundred only.\",\"grand_total\":654900,\"rounding_adjustment\":0,\"rounded_total\":654900,\"in_words\":\"INR Six Lakh, Fifty Four Thousand, Nine Hundred only.\",\"total_advance\":0,\"outstanding_amount\":654900,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"is_cash_or_non_trade_discount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"other_charges_calculation\":\"<div class=\\\"tax-break-up\\\" style=\\\"overflow-x: auto;\\\">\\n\\t<table class=\\\"table table-bordered table-hover\\\">\\n\\t\\t<thead>\\n\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-left\\\">HSN/SAC</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Taxable Amount</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Output Tax IGST</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t</tr>\\n\\t\\t</thead>\\n\\t\\t<tbody>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>94054090</td>\\n\\t\\t\\t\\t\\t<td class='text-right'>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t₹ 5,55,000.00\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class='text-right'>\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(18.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t₹ 99,900.00\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t</tbody>\\n\\t</table>\\n</div>\",\"total_billing_hours\":0,\"total_billing_amount\":0,\"base_paid_amount\":0,\"paid_amount\":0,\"base_change_amount\":0,\"change_amount\":0,\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"write_off_outstanding_amount_automatically\":0,\"redeem_loyalty_points\":0,\"loyalty_points\":0,\"loyalty_amount\":0,\"customer_address\":\"Kolkatta New-Billing\",\"address_display\":\"22, RABINDRA  SARANI, 1ST FLOOR,<br>ROOM NO FN9,<br>KOLKATA<br>\\nWest Bengal, State Code: 19<br>Pincode: 700073<br>India<br>\\nGSTIN: 19AAECP3318H1ZF<br>\",\"billing_address_gstin\":\"19AAECP3318H1ZF\",\"gst_category\":\"Registered Regular\",\"place_of_supply\":\"19-West Bengal\",\"territory\":\"India\",\"shipping_address_name\":\"kolkatta new-Billing-1\",\"shipping_address\":\"58 N S ROAD,<br>LILUAH, HOWRAH<br>HOWRAH<br>\\nWest Bengal, State Code: 19<br>Pincode: 711204<br>India<br>\\nGSTIN: 19AAECP3318H1ZF<br>\",\"company_address\":\"Blisstering Electronics Private Limited-Billing\",\"company_gstin\":\"09AAGCB7154D1ZQ\",\"company_address_display\":\"C 18, Sector 80<br>Noida<br>Gautam Buddha Nagar<br>\\nUttar Pradesh, State Code: 09<br>Pincode: 201306<br>India<br>\\nEmail: accounts01@blissteringepl.com<br>GSTIN: 09AAGCB7154D1ZQ<br>\",\"ignore_default_payment_terms_template\":0,\"po_no\":\"\",\"debit_to\":\"1310 - Debtors - BEPL\",\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"against_income_account\":\"4110 - Sales - BEPL\",\"amount_eligible_for_commission\":555000,\"commission_rate\":0,\"total_commission\":0,\"group_same_items\":0,\"invoice_copy\":\"Original for Recipient\",\"language\":\"en\",\"transporter\":\"SER2033\",\"gst_transporter_id\":\"09AAPCS9575E1ZL\",\"distance\":1433,\"transporter_name\":\"SER2033\",\"mode_of_transport\":\"Road\",\"lr_date\":\"2023-04-07\",\"gst_vehicle_type\":\"Regular\",\"status\":\"Unpaid\",\"einvoice_status\":\"Generated\",\"customer_group\":\"Commercial\",\"is_internal_customer\":0,\"is_discounted\":0,\"remarks\":\"No Remarks\",\"repost_required\":0,\"doctype\":\"Sales Invoice\",\"taxes\":[{\"name\":\"441c4a9b9b\",\"owner\":\"chetan.g@blissteringepl.com\",\"creation\":\"2023-04-07 15:00:35.585320\",\"modified\":\"2023-04-07 15:01:36.339711\",\"modified_by\":\"chetan.g@blissteringepl.com\",\"docstatus\":1,\"idx\":1,\"charge_type\":\"On Net Total\",\"account_head\":\"Output Tax IGST - BEPL\",\"description\":\"Output Tax IGST\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"cost_center\":\"Main - BEPL\",\"rate\":0,\"tax_amount\":99900,\"total\":654900,\"tax_amount_after_discount_amount\":99900,\"base_tax_amount\":99900,\"base_total\":654900,\"base_tax_amount_after_discount_amount\":99900,\"item_wise_tax_detail\":\"{\\\"FA-EMBL096501HL\\\":[18.0,99900.0]}\",\"dont_recompute_tax\":0,\"parent\":\"SINV/23-24/019\",\"parentfield\":\"taxes\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Taxes and Charges\"}],\"pricing_rules\":[],\"payment_schedule\":[{\"name\":\"2b2315a5e9\",\"owner\":\"chetan.g@blissteringepl.com\",\"creation\":\"2023-04-07 15:00:35.585320\",\"modified\":\"2023-04-07 15:01:36.339711\",\"modified_by\":\"chetan.g@blissteringepl.com\",\"docstatus\":1,\"idx\":1,\"payment_term\":\"15 Days\",\"due_date\":\"2023-04-22\",\"invoice_portion\":100,\"discount_type\":\"Percentage\",\"discount_date\":\"2023-04-07\",\"discount\":0,\"payment_amount\":654900,\"outstanding\":654900,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":654900,\"parent\":\"SINV/23-24/019\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Payment Schedule\"}],\"sales_team\":[],\"payments\":[],\"items\":[{\"name\":\"f2bb3e2542\",\"owner\":\"chetan.g@blissteringepl.com\",\"creation\":\"2023-04-07 15:00:35.585320\",\"modified\":\"2023-04-07 15:01:36.339711\",\"modified_by\":\"chetan.g@blissteringepl.com\",\"docstatus\":1,\"idx\":1,\"has_item_scanned\":0,\"item_code\":\"FA-EMBL096501HL\",\"item_name\":\"9W EMERGENCY BULB 6500K-HAVLOCK\",\"description\":\"9W EMERGENCY BULB 6500K-HAVLOCK\",\"gst_hsn_code\":\"94054090\",\"is_nil_exempt\":0,\"is_non_gst\":0,\"item_group\":\"Emergency Bulb\",\"image\":\"\",\"qty\":3000,\"stock_uom\":\"Nos\",\"uom\":\"Box\",\"conversion_factor\":1,\"stock_qty\":3000,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":185,\"amount\":555000,\"item_tax_template\":\"GST 18% - BEPL\",\"base_rate\":185,\"base_amount\":555000,\"stock_uom_rate\":185,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":185,\"net_amount\":555000,\"base_net_rate\":185,\"base_net_amount\":555000,\"taxable_value\":555000,\"delivered_by_supplier\":0,\"income_account\":\"4110 - Sales - BEPL\",\"is_fixed_asset\":0,\"expense_account\":\"5111 - Cost of Goods Sold - BEPL\",\"enable_deferred_revenue\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Finished Goods - BEPL\",\"incoming_rate\":0,\"allow_zero_valuation_rate\":0,\"item_tax_rate\":\"{\\\"Output Tax SGST - BEPL\\\": 9.0, \\\"Output Tax CGST - BEPL\\\": 9.0, \\\"Output Tax IGST - BEPL\\\": 18.0, \\\"1503 - Input Tax SGST - BEPL\\\": 9.0, \\\"1502 - Input Tax CGST - BEPL\\\": 9.0, \\\"1501 - Input Tax IGST - BEPL\\\": 18.0, \\\"1505 - Input Tax SGST RCM - BEPL\\\": 9.0, \\\"1504 - Input Tax CGST RCM - BEPL\\\": 9.0, \\\"1506 - Input Tax IGST RCM - BEPL\\\": 18.0}\",\"actual_batch_qty\":0,\"actual_qty\":3000,\"sales_order\":\"SO/23-24/00014\",\"so_detail\":\"a93abdee9b\",\"delivered_qty\":0,\"cost_center\":\"Main - BEPL\",\"page_break\":0,\"parent\":\"SINV/23-24/019\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\"}],\"timesheets\":[],\"advances\":[],\"packed_items\":[],\"__onload\":{\"make_payment_via_journal_entry\":0,\"e_waybill_info\":null,\"e_invoice_info\":null},\"__last_sync_on\":\"2023-04-07T09:35:11.072Z\"}",
		"print_format": "E Invoice",
		"no_letterhead": 1,
		"letterhead": "No Letterhead",
		"settings": "{}",
		"_lang": "en"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.www.printview.get_html_and_style"
}
```
### Response Data
```
{
	"exception": "jinja2.exceptions.UndefinedError: 'None' has no attribute 'signed_qr_code'"
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dineshpanchal93** [comment]
<img width="1175" alt="Screenshot 2023-04-07 at 3 11 58 PM" src="https://user-images.githubusercontent.com/21578167/230586419-f0a059e9-9f50-4f2b-b250-22e1dc5725d6.png">

**Comment by dineshpanchal93** [comment]
Suddenly we faced the issue.

**Comment by dineshpanchal93** [comment]
The E-invoice log is not being generated !!

**Comment by sagarvora** [comment]
- Check whether your background workers are running with `bench doctor` and `sudo supervisorctl status`
- Check **Error Log**
---
It's policy to close issues labelled as bugs that don't seem like bugs. But we can still discuss it here, and it may be reopened if later found to be a bug.
