### ISSUE TITLE
GST Settings - enable_e_invoice 

### ISSUE THREAD

**Issue by HnSSiva** [resilient-tech/india-compliance#581]
### Information about bug

Invalid Depends On Condition in 'Address-pincode-mandatory_depends_on', so the reflection in Sales Invoice as mentioned

Also we noticed similar kind of error when using GST Settings and Address DocTypes

### Version

ERPNext: v14.20.3 (version-14)
Frappe Framework: v14.31.0 (version-14)
India Compliance: v14.5.2 (version-14)

### Relevant log output / Stack trace / Full Error Message.

```shell
**Sales Invoice**

Uncaught (in promise) ReferenceError: gst_settings is not defined
    at frappe.listview_settings.<computed>.onload (sales_invoice__list_js:801:5)
    at frappe.views.ListView.setup_view (list_view.js:294:41)

**GST Settings**

let out =  india_compliance.is_api_enabled(doc); return out
eval @ utils.js:1089
evaluate_depends_on_value @ layout.js:715
refresh_dependency @ layout.js:633
refresh @ layout.js:321
refresh_fields @ form.js:654
(anonymous) @ form.js:606
Promise.then (async)
(anonymous) @ dom.js:262
frappe.run_serially @ dom.js:260
render_form @ form.js:598
(anonymous) @ form.js:567
Promise.then (async)
initialize_new_doc @ form.js:564
trigger_onload @ form.js:545
refresh @ form.js:429
render @ formview.js:117
(anonymous) @ formview.js:101
callback @ model.js:278
e @ request.js:85
200 @ request.js:128
(anonymous) @ request.js:294
R @ jquery.js:3500
fireWith @ jquery.js:3630
Oe @ jquery.js:9796
(anonymous) @ jquery.js:10057
load (async)
send @ jquery.js:10076
ajax @ jquery.js:9690
frappe.request.call @ request.js:268
frappe.call @ request.js:105
(anonymous) @ model.js:270
with_doc @ model.js:260
fetch_and_render @ formview.js:90
show_doc @ formview.js:85
make_and_show @ formview.js:32
(anonymous) @ formview.js:15
with_doctype @ model.js:190
make @ formview.js:12
show @ factory.js:25
render_page @ router.js:303
render @ router.js:282
route @ router.js:147
await in route (async)
set_route @ desk.js:168
startup @ desk.js:78
frappe.Application @ desk.js:30
frappe.start_app @ desk.js:12
(anonymous) @ desk.js:25
c1 @ jquery.js:3766
oe @ jquery.js:3834
setTimeout (async)
(anonymous) @ jquery.js:3872
R @ jquery.js:3500
fireWith @ jquery.js:3630
fire @ jquery.js:3638
R @ jquery.js:3500
fireWith @ jquery.js:3630
ready @ jquery.js:4110
h0 @ jquery.js:4120
messages.js:26 Uncaught (in promise) Error: Invalid "depends_on" expression
    at frappe.throw (messages.js:26:8)
    at frappe.ui.form.Layout.evaluate_depends_on_value (layout.js:720:12)
    at frappe.ui.form.Layout.refresh_dependency (layout.js:633:33)
    at frappe.ui.form.Layout.refresh (layout.js:321:8)
    at frappe.ui.form.Form.refresh_fields (form.js:654:15)
    at form.js:606:16
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
Hello,

We were able to replicate this issue, but it went away after building the latest JS assets. Please ensure that you're updating versions correctly. In this case, building the app's assets and refreshing the page resolved the issue:

```sh
bench build --app india_compliance
```

Tip: If you have a manual installation, it's best to update versions with `bench update`. If you still face the issue, feel free to comment here. We will reopen this issue.

**Comment by HnSSiva** [comment]
Thank you so much. We could able to fix the Issue based on your reply.
