### ISSUE TITLE
AttributeError: 'Gstr1Report' object has no attribute 'nil_exempt_non_gst'

### ISSUE THREAD

**Issue by sagarvora** [resilient-tech/india-compliance#678]
### App Versions
```
{
"erpnext": "14.24.0",
"frappe": "14.36.0",
"hrms": "14.3.1",
"india_compliance": "14.6.1",
}
```
### Route
```
query-report/GSTR-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 231, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/india_compliance/india_compliance/gst_india/report/gstr_1/gstr_1.py", line 19, in execute
    return Gstr1Report(filters).run()
  File "apps/india_compliance/india_compliance/gst_india/report/gstr_1/gstr_1.py", line 67, in run
    self.get_data()
  File "apps/india_compliance/india_compliance/gst_india/report/gstr_1/gstr_1.py", line 77, in get_data
    self.get_nil_rated_invoices()
  File "apps/india_compliance/india_compliance/gst_india/report/gstr_1/gstr_1.py", line 156, in get_nil_rated_invoices
    for invoice, details in self.nil_exempt_non_gst.items():
AttributeError: 'Gstr1Report' object has no attribute 'nil_exempt_non_gst'

```
### Request Data
```
{
"type": "GET",
"args": {
"report_name": "GSTR-1",
"filters": "{\"company\":\"Test Private Limited\",\"company_gstin\":\"27XXXXXXXXXXX6\",\"from_date\":\"2023-04-01\",\"to_date\":\"2023-04-30\",\"type_of_business\":\"NIL Rated\"}",
"are_default_filters": false
},
"headers": {},
"error_handlers": {},
"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
"exception": "AttributeError: 'Gstr1Report' object has no attribute 'nil_exempt_non_gst'"
}
```

**Comment by sagarvora** [comment]
Probably because user didn't have any nil rated invoices in the month of April. Because of that, the variable `nil_exempt_non_gst` never got [initialized](https://github.com/resilient-tech/india-compliance/blob/3a3000a282946478257b2940d907bc82b984a46b/india_compliance/gst_india/report/gstr_1/gstr_1.py#L408) although it was used later on.
