### ISSUE TITLE
Issue in printing eway bill

### ISSUE THREAD

**Issue by VARDHANA87** [resilient-tech/india-compliance#703]
eway bill is generated > Click on the eway bill print option 

Below mentioned error 

### App Versions
```
{
	"chat": "0.0.1",
	"erpnext": "14.24.3",
	"frappe": "14.36.1",
	"hrms": "14.3.2",
	"india_compliance": "14.7.0",
	"payments": "0.0.1",
	"suttati": "0.0.1"
}
```
### Route
```
print/e-Waybill Log/241593833721
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/www/printview.py", line 295, in get_html_and_style
    html = get_rendered_template(
  File "apps/frappe/frappe/www/printview.py", line 179, in get_rendered_template
    letter_head.content = frappe.utils.jinja.render_template(
  File "apps/frappe/frappe/utils/jinja.py", line 85, in render_template
    return get_jenv().from_string(template).render(context)
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 7, in top-level template code
TypeError: cannot unpack non-iterable NoneType object

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"241593833721\",\"owner\":\"mll@suttatti.com\",\"creation\":\"2023-05-22 18:10:16.546437\",\"modified\":\"2023-05-22 18:10:16.920962\",\"modified_by\":\"mll@suttatti.com\",\"docstatus\":0,\"idx\":0,\"e_waybill_number\":\"241593833721\",\"created_on\":\"2023-05-22 18:10:00\",\"valid_upto\":\"2023-05-23 23:59:00\",\"reference_doctype\":\"Sales Invoice\",\"reference_name\":\"U5/23-24/SI00072\",\"is_cancelled\":0,\"is_latest_data\":1,\"data\":\"{\\n    \\\"VehiclListDetails\\\": [\\n        {\\n            \\\"enteredDate\\\": \\\"22/05/2023 06:10:00 PM\\\",\\n            \\\"fromPlace\\\": \\\"Pune\\\",\\n            \\\"fromState\\\": 27,\\n            \\\"groupNo\\\": \\\"0\\\",\\n            \\\"transDocDate\\\": null,\\n            \\\"transDocNo\\\": \\\"\\\",\\n            \\\"transMode\\\": \\\"1\\\",\\n            \\\"tripshtNo\\\": 0,\\n            \\\"updMode\\\": \\\"API\\\",\\n            \\\"userGSTINTransin\\\": \\\"27AACCS4191H1Z8\\\",\\n            \\\"vehicleNo\\\": \\\"MH14EM6314\\\"\\n        }\\n    ],\\n    \\\"actFromStateCode\\\": 27,\\n    \\\"actToStateCode\\\": 27,\\n    \\\"actualDist\\\": 42,\\n    \\\"cessNonAdvolValue\\\": 0.0,\\n    \\\"cessValue\\\": 0.0,\\n    \\\"cgstValue\\\": 11456.9,\\n    \\\"docDate\\\": \\\"22/05/2023\\\",\\n    \\\"docNo\\\": \\\"U5/23-24/SI00072\\\",\\n    \\\"docType\\\": \\\"INV\\\",\\n    \\\"ewayBillDate\\\": \\\"22/05/2023 06:10:00 PM\\\",\\n    \\\"ewbNo\\\": 241593833721,\\n    \\\"extendedTimes\\\": 0,\\n    \\\"fromAddr1\\\": \\\"PLOT NO 109 TO 111, Sub Plot NO 8/9,\\\",\\n    \\\"fromAddr2\\\": \\\"SUTTATTI, RAMTEKADI INDUSTRIAL ESTATE,HADAPSAR,\\\",\\n    \\\"fromGstin\\\": \\\"27AACCS4191H1Z8\\\",\\n    \\\"fromPincode\\\": 411028,\\n    \\\"fromPlace\\\": \\\"Pune\\\",\\n    \\\"fromStateCode\\\": 27,\\n    \\\"fromTrdName\\\": \\\"Suttatti Enterprises Pvt Ltd unit 5\\\",\\n    \\\"genMode\\\": \\\"API\\\",\\n    \\\"igstValue\\\": 0.0,\\n    \\\"itemList\\\": [\\n        {\\n            \\\"cessNonAdvol\\\": 0.0,\\n            \\\"cessRate\\\": 0.0,\\n            \\\"cgstRate\\\": 14.0,\\n            \\\"hsnCode\\\": 72085120,\\n            \\\"igstRate\\\": 0,\\n            \\\"itemNo\\\": 1,\\n            \\\"productDesc\\\": \\\"B1DQA5011M00-Rev0\\\",\\n            \\\"productId\\\": 0,\\n            \\\"productName\\\": \\\"\\\",\\n            \\\"qtyUnit\\\": \\\"NOS\\\",\\n            \\\"quantity\\\": 5.0,\\n            \\\"sgstRate\\\": 14.0,\\n            \\\"taxableAmount\\\": 81835.0\\n        }\\n    ],\\n    \\\"noValidDays\\\": 1,\\n    \\\"otherValue\\\": 0.2,\\n    \\\"rejectStatus\\\": \\\"N\\\",\\n    \\\"sgstValue\\\": 11456.9,\\n    \\\"status\\\": \\\"ACT\\\",\\n    \\\"subSupplyType\\\": \\\"1  \\\",\\n    \\\"supplyType\\\": \\\"O\\\",\\n    \\\"toAddr1\\\": \\\"Plot No.D 236/7, MIDC Chakan Industrial\\\",\\n    \\\"toAddr2\\\": \\\"Plot No.D 236/7, MIDC Chakan Industrial\\\",\\n    \\\"toGstin\\\": \\\"27AAACT5566F1Z8\\\",\\n    \\\"toPincode\\\": 410501,\\n    \\\"toPlace\\\": \\\"PUNE\\\",\\n    \\\"toStateCode\\\": 27,\\n    \\\"toTrdName\\\": \\\"TATA TOYO RADIATOR LTD\\\",\\n    \\\"totInvValue\\\": 104749.0,\\n    \\\"totalValue\\\": 81835.0,\\n    \\\"transactionType\\\": 4,\\n    \\\"transporterId\\\": \\\"\\\",\\n    \\\"transporterName\\\": \\\"\\\",\\n    \\\"userGstin\\\": \\\"27AACCS4191H1Z8\\\",\\n    \\\"validUpto\\\": \\\"23/05/2023 11:59:00 PM\\\",\\n    \\\"vehicleType\\\": \\\"R\\\"\\n}\",\"doctype\":\"e-Waybill Log\",\"__last_sync_on\":\"2023-05-23T04:40:45.172Z\"}",
		"print_format": "e-Waybill",
		"no_letterhead": 0,
		"letterhead": "Sales Invoice",
		"settings": "{}",
		"_lang": "en"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.www.printview.get_html_and_style"
}
```
### Response Data
```
{
	"exception": "TypeError: cannot unpack non-iterable NoneType object"
}
```

Can contact me on 9480000338

**Comment by vorasmit** [comment]
Hi,

We need the following additional information to check if this is a valid bug.
This problem seems to be not related to e-Waybill print format.

- Are you able to use attach functionality from the e-Waybill dropdown?
- Are you able to use other sales invoice print formats?
- Does the issue persist after you remove the letterhead?
- Is this issue specific to one e-Waybill?

Its possible that the issue could be because of letterhead template.
We will be better able to assist if we can replicate this issue.

**Comment by vorasmit** [comment]
Closing this issue as no response received. Reopen with more details as requested.
