### ISSUE TITLE
GSPERR300 : Ei : GSPGSTDOWN

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#710]
### Information about bug

request.js:457 
        
       Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/india_compliance/india_compliance/gst_india/utils/e_invoice.py", line 109, in generate_e_invoice
    raise e
  File "apps/india_compliance/india_compliance/gst_india/utils/e_invoice.py", line 97, in generate_e_invoice
    result = api.generate_irn(data)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/e_invoice.py", line 67, in generate_irn
    result = self.post(endpoint="invoice", json=data)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 77, in post
    return self._make_request("POST", *args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 168, in _make_request
    raise e
  File "apps/india_compliance/india_compliance/gst_india/api_classes/base.py", line 157, in _make_request
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: GSPERR300 : Ei : GSPGSTDOWN

### Version

Frappe Chat: v0.0.1 (main)

ERPNext: v14.24.3 (version-14)

Frappe Framework: v14.36.1 (version-14)

Gatepass: v0.0.1 (main)

Frappe HR: v14.3.2 (version-14)

India Compliance: v14.7.0 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ganz007** [comment]
We are also facing this issue!

**Comment by dineshpanchal93** [comment]
@sagarvora any update ?

**Comment by sagarvora** [comment]
The issue you've mentioned happens because the API service is down on the Govt's side. In that scenario, neither the GSP (Adaequare) or the ASP (Resilient Tech) can do much about it. Our only recommendation when such an issue arises is to try again after sometime (maybe an hour or so).

**Comment by dineshpanchal93** [comment]
Yeah sure, No issue

Thanks for the support.
