### ISSUE TITLE
Company GSTIN is a mandatory field for GST Transactions error when creating Quotation from Leads, Prospects and Opportunities 

### ISSUE THREAD

**Issue by jpettan** [resilient-tech/india-compliance#813]
### Information about bug

We are unable to create quotations against a Lead/Prospect/Opportunity.

The Lead/prospect/opportunity doctype doesn’t capture Gst Registration type (Unregistered/registered) in the form.

This leads to the error “ Company GSTIN is a mandatory field for GST Transactions “ while creating a quotation from Lead / Prospect / Opportunity

Currently we are using the work around of creating a customer first and generate a quotation against a customer. Gst registration type is entered here and with this we are able to create quotation. This work around however distorts all sales reports.

We are looking for a solution to the issue.

### Version

Frappe version - 14.40.1
Erpnext version - 14.28.0
India compliance - 14.10.2

On FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Company GSTIN is a mandatory field for GST Transactions
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
Please share the full traceback.

**Comment by jpettan** [comment]
<img width="1366" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/115516364/8471d582-fc0e-4d53-bb22-cf9d286fc893">

**Comment by jpettan** [comment]
If this is not what you expect. Please guide me.

**Comment by jpettan** [comment]
New customer form - option to select unregistered gst customer.

<img width="1366" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/115516364/88398310-b8d2-4847-b693-57898c8666cb">

**Comment by vorasmit** [comment]
What is the GSTIN set in Company and Company Address?

**Comment by vorasmit** [comment]
Traceback is the Error traceback. Press F12 in the browser when receiving the error. You'll see an error traceback in the console. You need to share that, for us to inspect the origin of the error.

**Comment by jpettan** [comment]
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1248, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 764, in validate_transaction
    if validate_mandatory_fields(doc, ("company_gstin", "place_of_supply")) is False:
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 113, in validate_mandatory_fields
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 526, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 494, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 443, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: <strong>Company GSTIN</strong> is a mandatory field for GST Transactions

**Comment by vorasmit** [comment]
![image](https://github.com/resilient-tech/india-compliance/assets/10496564/504ec7a0-854a-4a74-8d79-2005e431c2ef)


Is GSTIN set in the company doctype and in the address used in the Quotation for the company?

**Comment by jpettan** [comment]
<img width="1366" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/115516364/e9f90e7b-6205-40b4-afe2-40b48509ff27">

**Comment by vorasmit** [comment]
![image](https://github.com/resilient-tech/india-compliance/assets/10496564/790948b4-03af-435c-8955-c77be6e5e04a)

Does it come up in Quotation Address?

**Comment by jpettan** [comment]
Yes.

<img width="1366" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/115516364/1e48e0e1-ce45-4371-91f0-2d38af970bd7">

**Comment by jpettan** [comment]
Hi,

Issue now resolved. We had to manually select the address and then submit the quotation.

**Comment by jpettan** [comment]
Thank you for your guidance.
