### ISSUE TITLE
Bug: setup wizard GSTIN sometimes assumes company exists

### ISSUE THREAD

**Issue by ankush** [resilient-tech/india-compliance#979]
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 82, in process_setup_stages
    task.get("fn")(task.get("args"))
  File "apps/india_compliance/india_compliance/setup_wizard.py", line 58, in setup_company_gstin_details
    update_company_info(params, gstin_info.gst_category)
  File "apps/india_compliance/india_compliance/setup_wizard.py", line 66, in update_company_info
    company_doc = frappe.get_cached_doc("Company", params.company_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1114, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1242, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 80, in get_doc
    return controller(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 121, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 173, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 546, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 518, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 467, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: Company XXXXX not found
{"language": "English", "country": "India", "timezone": "Asia/Kolkata", "currency": "INR", "enable_telemetry": 1, "full_name": "Harsh", "email": "", "password": "", "company_gstin": "27XXXXXXX", "company_name": "XXXXXXXXXXXXXXXXX", "company_abbr": "XXX", "chart_of_accounts": "India - Chart of Accounts", "fy_start_date": "2023-04-01", "fy_end_date": "2024-03-31", "setup_demo": 1, "enable_audit_trail": 0}
```

**Comment by sagarvora** [comment]
Is this happening because **India Compliance** is higher up in the `installed_apps` sequence for any reason? That could lead to the following output being reversed:

```py
In [1]: frappe.get_hooks("setup_wizard_stages")
Out[1]: 
['erpnext.setup.setup_wizard.setup_wizard.get_setup_stages',
 'india_compliance.setup_wizard.get_setup_wizard_stages']

```

**Comment by ankush** [comment]
@sagarvora I doubt it's even possible to install IC without installing ERPNext 😁 (is it?)


These are from trial site where IC is automatically installed if it's Indian user (mostly happens after, I'll check once)

**Comment by ankush** [comment]
@sagarvora 

```python
In [1]: frappe.get_installed_apps()
Out[1]: ['frappe', 'erpnext', 'india_compliance', 'email_delivery_service']

In [2]: frappe.get_hooks("setup_wizard_stages")
Out[2]:
['erpnext.setup.setup_wizard.setup_wizard.get_setup_stages',
 'india_compliance.setup_wizard.get_setup_wizard_stages']
```


Also one more source of error: `frappe.exceptions.ValidationError: GSTIN must have 15 characters`


IMO we can be tolerant here and skip setup if it fails (can always be done later)

**Comment by vorasmit** [comment]
I wasn't able to replicate this issue on Frappe Cloud:

## Nightly

### Setup
![image](https://github.com/resilient-tech/india-compliance/assets/10496564/44b62876-78b8-4f31-bcd8-b7d92f7feed9)

### Company
![image](https://github.com/resilient-tech/india-compliance/assets/10496564/5b18a074-b947-4ef7-901d-38f21ddb0237)

## Version-14

### Setup
![image](https://github.com/resilient-tech/india-compliance/assets/10496564/b9cfaa99-1c3d-4944-a3bc-448905856e33)

### Company
![image](https://github.com/resilient-tech/india-compliance/assets/10496564/962a7da6-625b-4498-955c-c414fa41372e)

**Comment by vorasmit** [comment]
Not sure how to replicate this. Created about 7-10 sites with different versions and variations but was not able to get this error.

**Comment by vorasmit** [comment]
Closing as couldn't be replicated.
